import{test,expect,type Page}from'@playwright/test';
async function start(page:Page,path='/me'){await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.emulateMedia({reducedMotion:'reduce'});await page.goto(path);}
async function settings(page:Page){await page.locator('summary').click();}
async function gate(page:Page){await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'18+专区',exact:true}).click();await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();}
async function qualify(page:Page){await start(page);await settings(page);await page.getByLabel('地区流程场景').selectOption('allowed');await gate(page);await expect(page.getByRole('button',{name:'确认并进入'})).toBeDisabled();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'确认并进入'}).click();await expect(page.locator('.adult-context')).toBeVisible();await expect(page.locator('.hero-poster')).toHaveCount(5);}
async function admin(page:Page){await start(page);await settings(page);await page.getByLabel('后台角色场景').selectOption('preview-admin');await page.getByRole('link',{name:'内容管理预览',exact:true}).click();await expect(page.getByRole('heading',{name:'内容管理',exact:true})).toBeVisible();}

test('public pages and protected direct URLs never request private preview catalog before qualification',async({page})=>{
 const requests:string[]=[],errors:string[]=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));await start(page,'/');
 for(const path of ['/','/shorts','/comics','/search?q=concept','/me','/18plus/play/private-preview-1','/play/private-preview-1','/play/%70rivate-preview-1','/18plus/search','/18plus/wishlist','/membership?context=adult']){await page.goto(path);await page.waitForTimeout(450);expect(await page.locator('[data-zone="adult"]').count()).toBe(0);expect(await page.locator('body').textContent()).not.toContain('专区概念卡');expect(await page.locator('img[src*="private-neutral"]').count()).toBe(0);}
 expect(requests.filter(u=>u.includes('adultPreview'))).toEqual([]);expect(errors).toEqual([]);await page.reload();await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();
});
for(const scenario of ['unknown','denied','error'])test(`region ${scenario} refuses premium and retry cannot grant`,async({page})=>{
 await start(page);await settings(page);await page.getByLabel('会员界面场景').selectOption('premium');await page.getByLabel('地区流程场景').selectOption(scenario);await gate(page);await page.getByRole('checkbox').check();await expect(page.getByRole('button',{name:'确认并进入'})).toBeDisabled();await page.getByRole('button',{name:'重试地区检查'}).click();await expect(page.getByRole('button',{name:'确认并进入'})).toBeDisabled();await page.keyboard.press('Escape');await expect(page).toHaveURL(/\/#home$/);await expect(page.locator('.hero-poster')).toHaveCount(5);
});
test('explicit gate, private tabs/search/wishlist, revoke and green return remain isolated',async({page})=>{
 await qualify(page);await page.getByRole('navigation',{name:'专区分类'}).getByRole('link',{name:'原创',exact:true}).click();await expect(page).toHaveURL(/tab=original/);await expect(page.locator('#adult-catalog .drama-card')).toHaveCount(3);
 await page.getByRole('link',{name:'专区搜索',exact:true}).click();await page.getByRole('button',{name:'开启专区搜索'}).click();const input=page.getByLabel('专区关键词');await input.dispatchEvent('compositionstart');await input.fill('保密查询');await input.dispatchEvent('keydown',{key:'Enter',isComposing:true});await expect(page).toHaveURL(/\/18plus\/search$/);await input.dispatchEvent('compositionend');await page.getByRole('button',{name:'搜索',exact:true}).click();await expect(page.getByRole('heading',{name:'没有找到相关内容'})).toBeVisible();
 const storage=await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage},state:history.state}));expect(storage).not.toContain('保密查询');expect(storage).not.toContain('private-preview');
 await page.getByRole('button',{name:'清空',exact:true}).click();await page.locator('.drama-card').first().click();await expect(page.locator('video,.episode-panel')).toHaveCount(0);await page.getByRole('button',{name:'加入私密愿望榜'}).click();await page.getByRole('link',{name:'返回专区',exact:true}).click();await page.getByRole('link',{name:'私密愿望榜',exact:true}).click();await expect(page.locator('.private-record')).toHaveCount(1);await page.getByRole('button',{name:'记录本地预约',exact:true}).click();await expect(page.getByRole('button',{name:'已记录本地预约'})).toBeDisabled();await page.getByRole('button',{name:'移出愿望榜'}).click();await page.getByRole('button',{name:'确认移出'}).click();await expect(page.locator('.private-record')).toHaveCount(0);
 await page.getByRole('button',{name:'退出18+专区'}).click();await expect(page).toHaveURL(/\/#home$/);await expect(page.locator('[data-zone="adult"]')).toHaveCount(0);await page.goBack();await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();
});
test('cross-tab revocation, expiry, storage tampering and delayed consent never retain access',async({page,context})=>{
 await qualify(page);const other=await context.newPage();await start(other);await settings(other);await other.getByRole('button',{name:'模拟会话到期 / 撤销资格'}).click();await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();await other.close();
 await page.evaluate(()=>{localStorage.setItem('adultGranted','true');sessionStorage.setItem('aiai:age-verified','yes');});await page.reload();await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();await expect(page.locator('.adult-context')).toHaveCount(0);
 const race=await page.evaluate(async()=>{const{accessService}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/access.ts')||'/src/services/access.ts');accessService.setPreviewScenario('allowed');const pending=accessService.enter(true,true);accessService.revoke();return await pending;});expect(race).toBe(false);
 await page.clock.install();await page.evaluate(async()=>{const{accessService}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/access.ts')||'/src/services/access.ts');accessService.setPreviewScenario('allowed');});await page.clock.resume();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'确认并进入'}).click();await expect(page.locator('.adult-context')).toBeVisible();await page.clock.fastForward(600001);await expect(page.getByRole('heading',{name:'进入18+专区前'})).toBeVisible();
});
test('route cancellation prevents late private data or consent from mounting',async({page})=>{
 await start(page);await settings(page);await page.getByLabel('地区流程场景').selectOption('allowed');await gate(page);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'确认并进入'}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'首页',exact:true}).click();await page.waitForTimeout(700);await expect(page.locator('.adult-context,[data-zone="adult"]')).toHaveCount(0);expect(await page.evaluate(async()=>{const{accessService}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/access.ts')||'/src/services/access.ts');return accessService.isGranted();})).toBe(false);
});
test('membership A/B quotes match, upgrade includes base, unavailable checkout creates no order',async({page})=>{
 for(const [group,prices]of [['A',[19,39,99]],['B',[29,49,129]]]as const){await start(page);await settings(page);await page.getByLabel('会员界面场景').selectOption('basic');await page.getByLabel('价格实验场景').selectOption(group);await page.getByRole('link',{name:'会员中心',exact:true}).first().click();await expect(page.locator('.plan-card')).toHaveCount(3);
 for(let i=0;i<3;i++){await expect(page.locator('.plan-price').nth(i)).toContainText(String(prices[i]));await page.locator('.plan-card button').nth(i).click();await expect(page.locator('.confirmation-price')).toContainText(String(prices[i]));await page.getByRole('button',{name:'查看开通状态'}).click();await expect(page.getByRole('status')).toContainText('未创建订单或扣费');await page.keyboard.press('Escape');}
 await expect(page.locator('.membership-current')).toContainText('基础权益已包含');await page.getByRole('link',{name:'我的订单',exact:true}).click();await expect(page.getByRole('heading',{name:'暂无订单'})).toBeVisible();}
});
test('privacy hide differs from confirmed removal and clear; events do not contain raw sensitive input',async({page})=>{
 await start(page,'/play/preview-01');await page.getByRole('button',{name:'记录本地关注'}).click();await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'我的',exact:true}).click();await expect(page.locator('#green-records .drama-card')).toHaveCount(1);await page.getByRole('link',{name:'管理本地记录'}).click();await page.getByLabel('隐藏精选关注').check();await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'我的',exact:true}).click();await expect(page.getByRole('heading',{name:'关注记录已隐藏'})).toBeVisible();await page.getByRole('link',{name:'管理本地记录'}).click();await page.getByLabel('隐藏精选关注').uncheck();await page.getByRole('button',{name:'移除',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'移除',exact:true})).toBeVisible();await page.getByRole('button',{name:'清空本地精选记录'}).click();await page.getByRole('button',{name:'确认清除',exact:true}).click();await expect(page.getByRole('status')).toContainText('已清除本地演示记录');await expect(page.getByRole('button',{name:'移除',exact:true})).toHaveCount(0);
 const events=await page.evaluate(async()=>{const{track,previewEvents}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/analytics.ts')||'/src/services/analytics.ts');track({name:'search_submit',zone:'adult',query:'PRIVATE SECRET',title:'PRIVATE SECRET',route:'/18plus/search?q=PRIVATE SECRET'}as any);track({name:'upgrade_success',zone:'green'});return previewEvents();});expect(JSON.stringify(events)).not.toContain('PRIVATE SECRET');expect(events.some(e=>e.name==='upgrade_success')).toBe(false);
});
for(const [width,height]of [[320,812],[390,844],[768,1024],[1280,720],[1920,1080]])test(`M4 CMS, analytics, membership, gate and privacy layout ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await admin(page);await page.getByRole('button',{name:'新建草稿'}).click();await page.getByRole('button',{name:'校验并模拟发布'}).click();await expect(page.locator('#validation-summary')).toBeFocused();await expect(page.locator('#validation-summary')).toContainText('请选择内容域');await expect(page.getByRole('button',{name:'正式发布未接入'})).toBeDisabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===320||width===1280)await page.screenshot({path:`docs/m4/screenshots/${width}-cms-errors.png`,fullPage:true});await page.getByLabel('内容格式').selectOption('article');await expect(page.getByLabel('文章正文')).toBeVisible();await expect(page.getByLabel('片源地址')).toHaveCount(0);await page.getByLabel('作品名称').fill('本地文章草稿');await page.getByLabel('文章正文').fill('仅在后台预览的文本。');await page.getByRole('button',{name:'预览',exact:true}).click();await expect(page.locator('dialog article')).toContainText('仅在后台');await expect(page.locator('video')).toHaveCount(0);await page.keyboard.press('Escape');
 const service=await page.evaluate(async()=>{const{simulatePublish}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/publishing.ts')||'/src/services/publishing.ts');return simulatePublish({title:'Bypass attempt'});});expect(service.ok).toBe(false);expect(service.issues.length).toBeGreaterThan(0);
 await page.getByRole('link',{name:'数据分析',exact:true}).click();await expect(page.locator('.metric-card')).toHaveCount(10);await expect(page.locator('.metric-card').first()).toContainText('暂无数据');if(width===320||width===1280)await page.screenshot({path:`docs/m4/screenshots/${width}-analytics.png`,fullPage:true});
 for(const path of ['/membership','/me/privacy','/18plus']){await page.goto(path);await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
test('small carousel catalogs render no clones or invalid controls, survive length changes',async({page})=>{
 await page.route('**/src/main.tsx*',async route=>{const module=await(await page.request.get('/src/components/Carousel.tsx')).text();const routerURL=module.match(/from ["']([^"']*\/navigation\/Router\.tsx[^"']*)/)! [1];return route.fulfill({contentType:'application/javascript',body:`import React from'/node_modules/.vite/deps/react.js';import ReactDOM from'/node_modules/.vite/deps/react-dom_client.js';const{useState}=React;const{createRoot}=ReactDOM;import{Carousel}from'/src/components/Carousel.tsx';import{Router}from'${routerURL}';import{previewCatalog}from'/src/data/previewCatalog.ts';import'/src/styles.css';function Fixture(){const[n,set]=useState(0);return React.createElement(React.Fragment,null,...[0,1,2,3,4,5].map(i=>React.createElement('button',{key:i,onClick:()=>set(i)},'Count '+i)),React.createElement(Carousel,{items:previewCatalog.slice(0,n),initialIndex:99,reduced:true,blocked:false}));}createRoot(document.getElementById('root')).render(React.createElement(Router,null,React.createElement(Fixture)));`});});await page.goto('/');
 for(const n of [0,1,2,3,4,5,2,0]){await page.getByRole('button',{name:`Count ${n}`,exact:true}).click();await expect(page.locator('.hero-poster')).toHaveCount(n);await expect(page.locator('.carousel-dots button')).toHaveCount(n>1?n:0);if(n>1){await page.getByRole('button',{name:'下一部短剧'}).click();const ids=await page.locator('.hero-poster').evaluateAll(els=>els.map(e=>e.getAttribute('data-drama-id')));expect(new Set(ids).size).toBe(n);await expect(page.locator('.offset-0')).toHaveCount(1);}}
});

test('catalog filters, refresh, history and configured loading errors retain usable states',async({page})=>{
 await start(page,'/comics');await page.getByRole('combobox',{name:'题材',exact:true}).selectOption('科幻');await expect(page.locator('.drama-card')).toHaveCount(2);await page.getByRole('combobox',{name:'排序',exact:true}).selectOption('title');await page.reload();await expect(page.getByRole('combobox',{name:'题材',exact:true})).toHaveValue('科幻');await expect(page.getByRole('combobox',{name:'排序',exact:true})).toHaveValue('title');await page.locator('.drama-card').last().scrollIntoViewIfNeeded();const scroll=await page.evaluate(()=>scrollY);await page.locator('.drama-card').last().click();await page.goBack();await expect(page.locator('.drama-card')).toHaveCount(2);expect(Math.abs(await page.evaluate(()=>scrollY)-scroll)).toBeLessThan(8);
 await page.getByRole('combobox',{name:'更新状态',exact:true}).selectOption('completed');await expect(page.locator('.empty-state')).toBeVisible();await page.getByRole('button',{name:'重置筛选'}).click();await expect(page.locator('.drama-card')).toHaveCount(5);
 await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'我的',exact:true}).click();await settings(page);await page.getByLabel('内容加载场景').selectOption('error');await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'短剧',exact:true}).click();await expect(page.getByText('本地预览：内容加载失败，请重试')).toBeVisible();await page.evaluate(async()=>{const{contentService}=await import(performance.getEntriesByType('resource').map(e=>e.name).find(url=>new URL(url).pathname==='/src/services/content.ts')||'/src/services/content.ts');contentService.setPreviewScenario('ready');});await page.getByRole('button',{name:'重试',exact:true}).click();await expect(page.locator('.drama-card')).toHaveCount(5);
 await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'我的',exact:true}).click();await settings(page);await page.getByLabel('内容加载场景').selectOption('empty');await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'首页',exact:true}).click();await expect(page.locator('.hero-empty')).toBeVisible();await expect(page.locator('.hero-poster')).toHaveCount(0);
});
