import {test,expect} from '@playwright/test';
for(const width of [320,390,768,1280,1920])test('cards and five rows '+width,async({page})=>{
 await page.setViewportSize({width,height:950});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/18plus');await page.getByRole('button',{name:'确认并进入'}).click();await expect(page.locator('#adult-catalog .adult-card')).toHaveCount(6);
 await expect(page.locator('header').getByText('返回普通区')).toHaveCount(0);await expect(page.getByRole('button',{name:'隐私设置'})).toHaveCount(0);
 const metrics=await page.locator('#adult-catalog .adult-card').first().evaluate(e=>{const t=e.querySelector('h3')!,p=e.querySelector('p')!,s=getComputedStyle(p);return{gap:p.getBoundingClientRect().top-t.getBoundingClientRect().bottom,lines:p.getBoundingClientRect().height/parseFloat(s.lineHeight),width:e.getBoundingClientRect().width}});expect(metrics.gap).toBeCloseTo(12);expect(metrics.lines).toBeCloseTo(2);expect((await page.locator('#adult-latest .adult-card').first().boundingBox())!.width).toBeCloseTo(metrics.width);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('header nav').getByRole('link',{name:'成人短剧',exact:true}).click();const count=(width>1100?4:width>760?3:2)*5;await expect(page.locator('#adult-catalog .adult-card')).toHaveCount(count);
 expect(new Set(await page.locator('#adult-catalog .adult-card').evaluateAll(es=>es.map(e=>Math.round(e.getBoundingClientRect().top)))).size).toBe(5);
 const first=await page.locator('.adult-card-title').first().innerText();await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page).toHaveURL(/page=2/);await expect(page.locator('.adult-card-title').first()).not.toHaveText(first);await page.reload();await expect(page.getByRole('button',{name:'第2页',exact:true})).toHaveAttribute('aria-current','page');await page.goBack();await expect(page.getByRole('button',{name:'第1页',exact:true})).toHaveAttribute('aria-current','page');
 await expect(page.locator('.brand-zone-mark')).toBeVisible();const badge=await page.locator('.brand-zone-mark').boundingBox(),actions=await page.locator('.header-actions').boundingBox();expect(badge!.x+badge!.width).toBeLessThanOrEqual(actions!.x);await page.locator('header').screenshot({path:'docs/adult-covers/header-'+width+'.png'});await page.locator('.adult-card').first().screenshot({path:'docs/adult-covers/card-'+width+'.png'});expect(errors).toEqual([]);
});
test('all categories, filters reset page and logo returns ordinary home',async({page})=>{await page.goto('/18plus');await page.getByRole('button',{name:'确认并进入'}).click();for(const label of ['成人短剧','成人漫剧','原创','最新','热门']){await page.locator('header nav').getByRole('link',{name:label,exact:true}).click();await expect(page.locator('#adult-catalog .adult-card')).toHaveCount(20);await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page).toHaveURL(/page=2/);}await page.getByRole('group',{name:'题材',exact:true}).getByRole('button',{name:'悬疑',exact:true}).click();await expect(page).not.toHaveURL(/page=2/);await page.locator('.site-header .brand').click();await expect(page).toHaveURL(/\/#home$/);});

test('unique artwork across catalogue and pages; breadcrumb returns adult home',async({page})=>{await page.goto('/18plus');await page.getByRole('button',{name:'确认并进入'}).click();const sources=await page.locator('.adult-body .adult-card img').evaluateAll(es=>es.map(e=>e.getAttribute('src')));expect(new Set(sources).size).toBe(sources.length);await expect(page.locator('#adult-latest-title')).toHaveText('最近上新');await page.locator('header nav').getByRole('link',{name:'成人短剧',exact:true}).click();const first=await page.locator('#adult-catalog .adult-card img').evaluateAll(es=>es.map(e=>e.getAttribute('src')));await page.getByRole('button',{name:'下一页',exact:true}).click();const second=await page.locator('#adult-catalog .adult-card img').evaluateAll(es=>es.map(e=>e.getAttribute('src')));expect(first.some(s=>second.includes(s))).toBe(false);await page.locator('.adult-card-title').first().click();await expect(page.locator('.breadcrumb a')).toHaveAttribute('href','/18plus');await page.locator('.breadcrumb a').click();await expect(page).toHaveURL(/18plus$/);await page.getByRole('link',{name:'愿望榜',exact:true}).click();await expect(page.locator('.breadcrumb a')).toHaveAttribute('href','/18plus');});
