import {test,expect} from '@playwright/test';
test('autoplay yields to real hover, manual pause, modal and page visibility',async({page})=>{
  await page.route('**/src/config.ts*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('carousel: 5e3','carousel: 350').replace('carousel: 5000','carousel: 350')});});
  await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.goto('/');await page.locator('.hero').waitFor();await page.mouse.move(710,350);
  const id=await page.locator('.offset-0').getAttribute('data-drama-id');await page.waitForTimeout(850);await expect(page.locator('.offset-0')).toHaveAttribute('data-drama-id',id!);
  await page.getByRole('button',{name:'下一部短剧'}).click();await expect(page.locator('.hero')).toHaveAttribute('data-motion','idle');const selected=await page.locator('.offset-0').getAttribute('data-drama-id');await page.getByRole('textbox',{name:'搜索精选内容'}).focus();await page.mouse.move(980,40);await page.waitForTimeout(850);await expect(page.locator('.offset-0')).toHaveAttribute('data-drama-id',selected!);
  await page.getByRole('button',{name:'继续自动轮播'}).click();await page.getByRole('textbox',{name:'搜索精选内容'}).focus();await page.mouse.move(980,40);await expect(page.locator('.offset-0')).not.toHaveAttribute('data-drama-id',selected!);
  await page.getByRole('button',{name:'登录 / 注册',exact:true}).click();const blocked=await page.locator('.offset-0').getAttribute('data-drama-id');await page.waitForTimeout(900);await expect(page.locator('.offset-0')).toHaveAttribute('data-drama-id',blocked!);await page.keyboard.press('Escape');await expect(page.locator('dialog')).toHaveCount(0);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});const hidden=await page.locator('.offset-0').getAttribute('data-drama-id');await page.waitForTimeout(900);await expect(page.locator('.offset-0')).toHaveAttribute('data-drama-id',hidden!);expect(await page.locator('.hero-poster').evaluateAll(els=>els.flatMap(e=>e.getAnimations()).filter(a=>a.playState==='running').length)).toBe(0);
});
test('brand intro still completes once and does not replay after player return',async({page})=>{
  await page.goto('/');await expect(page.locator('.intro')).toBeVisible();await page.getByRole('button',{name:'进入爱爱',exact:true}).click();await expect(page.locator('.intro')).toHaveCount(0,{timeout:5000});await expect(page.locator('.nav-logo')).toHaveCSS('visibility','visible');expect(await page.evaluate(()=>document.body.style.overflow)).toBe('');
  await page.locator('.offset-0 a').click();await expect(page).toHaveURL(/\/play\//);await page.goBack();await expect(page.locator('.hero')).toBeVisible();await expect(page.locator('.intro')).toHaveCount(0);await expect(page.getByRole('button',{name:'重放品牌开屏'})).toHaveCount(0);
});
test('resize settles current motion but the next normal step still animates',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.goto('/');await page.getByRole('button',{name:'下一部短剧'}).click();await page.setViewportSize({width:1024,height:900});await expect(page.locator('.hero')).toHaveAttribute('data-motion','idle');await page.setViewportSize({width:1920,height:1000});await page.getByRole('button',{name:'下一部短剧'}).click();await expect(page.locator('.hero')).toHaveAttribute('data-motion','moving');expect(await page.locator('.hero-poster').evaluateAll(els=>els.flatMap(e=>e.getAnimations()).filter(a=>a.playState==='running').length)).toBeGreaterThan(0);await expect(page.locator('.hero')).toHaveAttribute('data-motion','idle');
});
