import{test,expect}from'@playwright/test';

test.beforeEach(async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));});

test('游客页头、页脚和兼容路由完整',async({page})=>{await page.goto('/me');await expect(page).toHaveTitle('我的');await expect(page.getByRole('link',{name:'签到，领积分'})).toHaveAttribute('href','/account/login?returnTo=%2Fme%23daily-check-in');await expect(page.locator('.points-trigger,.points-popover,.festival-header-link')).toHaveCount(0);await expect(page.getByRole('contentinfo')).toContainText('入夜之后，好戏登场');for(const route of ['/help','/contact','/videos']){await page.goto(route);await expect(page.getByText('没有找到这个页面')).toHaveCount(0);}});

test('登录用户看到动态中心、七日奖励和改密校验',async({page})=>{const account=`me${Date.now().toString(36)}`,password='safe-pass-123';await page.goto(`/account/register?returnTo=${encodeURIComponent('/me')}`);await page.getByLabel('账号',{exact:true}).fill(account);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByLabel('确认密码',{exact:true}).fill(password);await page.getByRole('button',{name:'创建账号'}).click();await expect(page.getByRole('heading',{name:'每日签到，攒积分追好剧'})).toBeVisible();await expect(page.locator('.check-in-week li')).toHaveCount(7);await expect(page.locator('.permanent-credits')).not.toContainText('免费用户付费单集');await expect(page.locator('.trial-card')).not.toContainText('符合资格，可领取一次');await expect(page.locator('.trial-card')).not.toContainText('18+ 内容仍需年龄与地区确认');await expect(page.locator('.account-shortcut-grid>a')).toHaveCount(8);await page.getByRole('button',{name:'立即签到'}).click();await expect(page.locator('#daily-check-in')).not.toContainText('今天已获得 1 永久积分');await page.getByRole('button',{name:'修改密码'}).click();await page.getByRole('button',{name:'保存新密码'}).click();await expect(page.getByText('请输入当前密码。')).toBeVisible();await expect(page.getByText('新密码需为 8–64 个字符。')).toBeVisible();});

test('320与1440视口无页面横向溢出',async({page})=>{for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('/me');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();}});
