import {test,expect,type Page} from '@playwright/test';
import {newWallet,grantMonthly,checkIn,unlock,topUp,walletData,type PointsWallet} from '../src/services/pointsModel';
import type {Tier} from '../src/types/content';
const now=new Date();
async function mock(page:Page,tier:Tier='free',balance?:number){
 let signed=true,currentTier=tier;const wallet:PointsWallet=newWallet();grantMonthly(wallet,'points-user',tier,now);if(balance!==undefined)wallet.pointsBalance=balance;
 await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname,body=route.request().postDataJSON()??{};
  if(path==='/api/v1/session'){if(route.request().method()==='DELETE')signed=false;await route.fulfill({json:{subject:signed?'points-user':null,nickname:'积分测试用户',tier:currentTier,roles:[],expiresAt:null}});return;}
  if(path.includes('/me/points')||path.endsWith('/unlock')){
   if(path.endsWith('/check-in'))checkIn(wallet,now);
   if(path.endsWith('/unlock')){const ids=path.split('/');try{unlock(wallet,{contentId:ids[4],episodeId:ids[6],contentTitle:'凋零前，请对我偏执',episodeTitle:'第7集',coverUrl:'/assets/covers/drama-05.webp',href:'/play/drama-05?episode=demo-7'},10,currentTier,body.idempotencyKey,now);}catch{await route.fulfill({status:409,json:{code:'insufficient_points'}});return;}}
   if(path.endsWith('/demo-purchase')){if(body.offerId.startsWith('points-'))topUp(wallet,body.offerId,body.idempotencyKey,now);else{currentTier=body.offerId.startsWith('joy')?'basic':'premium';grantMonthly(wallet,'points-user',currentTier,now);}}
   await route.fulfill({json:walletData(wallet,currentTier,now)});return;
  }
  await route.fulfill({status:200,json:path==='/api/v1/comments'?{items:[],cursor:null}:[]});
 });return wallet;
}
test('访客隐藏积分，保留会员中心与登录，详情登录回跳',async({page})=>{await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.goto('/#home');await expect(page.locator('.points-trigger')).toHaveCount(0);await expect(page.locator('header').getByRole('link',{name:'会员中心'})).toHaveText('会员中心');await expect(page.locator('header').getByRole('button',{name:'登录 / 注册'})).toBeVisible();await page.goto('/me/points');await expect(page.getByRole('dialog')).toBeVisible();await expect(page).toHaveURL(/returnTo=%2Fme%2Fpoints/);});
test('浮层 hover、点击、键盘、外部关闭；签到确认、去重和刷新',async({page})=>{const wallet=await mock(page);await page.goto('/#home');const trigger=page.locator('.points-trigger'),popover=page.getByRole('region',{name:'积分账户'});await expect(trigger).toHaveText('40');await trigger.hover();await expect(popover).toBeVisible();await popover.hover();await expect(popover.getByText('免费用户')).toBeVisible();await trigger.click();await trigger.click();await expect(popover).toBeHidden();await trigger.press('Enter');await expect(popover).toBeVisible();await trigger.press('Escape');await expect(popover).toBeHidden();await trigger.press('Space');await expect(popover).toBeVisible();await page.locator('main').first().click({position:{x:5,y:5}});await expect(popover).toBeHidden();await trigger.click();await page.getByRole('button',{name:'去签到',exact:true}).click();await expect(page.getByRole('dialog',{name:'每日签到'})).toBeVisible();expect(wallet.pointsBalance).toBe(40);await page.getByRole('button',{name:'确认签到'}).click();await expect(page.getByRole('heading',{name:'签到成功'})).toBeVisible();await expect(trigger).toHaveText('45');await page.getByRole('button',{name:'完成'}).click();await page.reload();await expect(trigger).toHaveText('45');await trigger.hover();await expect(page.getByRole('button',{name:'今日已签到'})).toBeDisabled();expect(wallet.transactions.filter(t=>t.type==='check_in')).toHaveLength(1);});
for(const tier of ['basic','premium'] as const)test(`${tier}展示正确名称、积分及充值入口`,async({page})=>{await mock(page,tier);await page.goto('/me/points');await page.locator('.points-trigger').hover();await expect(page.getByRole('region').getByRole('link',{name:'充值',exact:true})).toHaveAttribute('href',/view=points/);await expect(page.locator('.points-trigger')).toHaveText(tier==='basic'?'320':'960');await expect(page.locator('header .account-avatar-link')).toHaveAttribute('title',tier==='basic'?'悦享会员':'尊享会员');});
test('积分解锁、自动播放、永久记录、明细与余额同步',async({page})=>{const wallet=await mock(page);await page.goto('/play/drama-05');await page.getByRole('button',{name:'第7集，需10积分解锁',exact:true}).click();await expect(page.getByRole('dialog',{name:'解锁第7集'})).toBeVisible();await page.getByRole('button',{name:'确认解锁'}).click();await expect(page.locator('.points-trigger')).toHaveText('30');await expect(page.locator('video')).toBeVisible();await expect(page).toHaveURL(/episode=demo-7/);await page.getByRole('button',{name:'第7集',exact:true}).click();expect(wallet.unlocks).toHaveLength(1);await page.reload();await expect(page.getByRole('button',{name:'第7集',exact:true})).toHaveAttribute('aria-current','true');await page.goto('/me/points');await expect(page.getByRole('link',{name:'继续观看'})).toBeVisible();await page.getByRole('button',{name:'积分明细'}).click();await expect(page.getByText('交易后余额：30')).toBeVisible();await expect(page.getByText('-10',{exact:true})).toBeVisible();});
for(const tier of ['free','premium'] as const)test(`${tier}积分不足入口及充值返回原剧集`,async({page})=>{await mock(page,tier,1);await page.goto('/play/drama-05');await page.getByRole('button',{name:new RegExp('第7集，需')}).click();const dialog=page.getByRole('dialog',{name:'积分不足'});await expect(dialog).toBeVisible();await dialog.getByRole('link',{name:tier==='free'?'开通会员':'充值积分',exact:true}).click();if(tier==='free')await page.getByRole('button',{name:'立即开通'}).click();else await page.getByRole('button',{name:'60 积分 ¥6'}).click();await page.getByRole('button',{name:'确认演示购买'}).click();await expect(page).toHaveURL(/play\/drama-05\?episode=demo-7/);});
test('积分服务失败重试、签到失败不增分',async({page})=>{const wallet=await mock(page);await page.route('**/api/v1/me/points',r=>r.fulfill({status:503,json:{code:'service_unavailable'}}));await page.goto('/me/points');await expect(page.getByRole('button',{name:'重新加载积分'}).first()).toBeVisible();await page.unroute('**/api/v1/me/points');await page.getByRole('button',{name:'重新加载积分'}).first().click();await page.getByRole('button',{name:'去签到',exact:true}).click();await page.route('**/api/v1/me/points/check-in',r=>r.fulfill({status:503,json:{code:'service_unavailable'}}));await page.getByRole('button',{name:'确认签到'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();expect(wallet.pointsBalance).toBe(40);await expect(page.getByRole('button',{name:'确认签到'})).toBeEnabled();});
test('1440与390视觉、低高度、触屏操作及无控制台错误',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const wallet=await mock(page,'premium');wallet.pointsBalance=123456;await page.emulateMedia({reducedMotion:'reduce'});for(const width of [1440,390]){await page.setViewportSize({width,height:844});await page.goto('/me/points');await page.locator('.points-trigger').click();await expect(page.getByRole('region',{name:'积分账户'})).toBeVisible();await expect(page.getByRole('region').getByText('123456',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`.local/points-${width}.png`,fullPage:true});await page.getByRole('region').getByRole('button',{name:'去签到'}).click();await page.screenshot({path:`.local/points-checkin-${width}.png`});await page.keyboard.press('Escape');}await page.setViewportSize({width:390,height:320});await page.locator('.points-trigger').click();const box=await page.getByRole('region').boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(320);expect(errors).toEqual([]);});

test('登出清除余额，切换账号不显示前一个账号的记录',async({page})=>{const wallet=await mock(page);unlock(wallet,{contentId:'drama-05',episodeId:'demo-7',contentTitle:'旧账号的剧集',episodeTitle:'第7集',coverUrl:null,href:'/play/drama-05?episode=demo-7'},10,'free','old');await page.goto('/me/points');await expect(page.getByText('旧账号的剧集')).toBeVisible();await page.goto('/me');await page.getByRole('button',{name:'退出账号'}).click();await expect(page.locator('.points-trigger')).toHaveCount(0);const next=newWallet();grantMonthly(next,'new-user','free');await page.route('**/api/v1/session',r=>r.fulfill({json:{subject:'new-user',nickname:'新账号',tier:'free',roles:[],expiresAt:null}}));await page.route('**/api/v1/me/points',r=>r.fulfill({json:walletData(next,'free')}));await page.goto('/me/points');await expect(page.locator('.points-trigger')).toHaveText('40');await expect(page.getByText('旧账号的剧集')).toHaveCount(0);await expect(page.getByRole('heading',{name:'还没有解锁记录'})).toBeVisible();});

test('其他设备先签到：刷新为已签到；解锁时余额变化与内容下架不扣费',async({page})=>{const wallet=await mock(page);await page.goto('/me/points');await page.getByRole('button',{name:'去签到',exact:true}).click();checkIn(wallet);await page.route('**/api/v1/me/points/check-in',r=>r.fulfill({json:{...walletData(wallet,'free'),reward:0}}));await page.getByRole('button',{name:'确认签到'}).click();await expect(page.getByRole('heading',{name:'今日已签到'})).toBeVisible();await expect(page.locator('.points-trigger')).toHaveText('45');await page.getByRole('button',{name:'完成'}).click();await page.goto('/play/drama-05');await page.getByRole('button',{name:'第7集，需10积分解锁',exact:true}).click();wallet.pointsBalance=1;await page.getByRole('button',{name:'确认解锁'}).click();await expect(page.getByRole('dialog',{name:'积分不足'})).toBeVisible();expect(wallet.unlocks).toHaveLength(0);await page.keyboard.press('Escape');wallet.pointsBalance=40;await page.reload();await page.getByRole('button',{name:'第7集，需10积分解锁',exact:true}).click();await page.route('**/episodes/*/unlock',r=>r.fulfill({status:404,json:{code:'content_unavailable'}}));await page.getByRole('button',{name:'确认解锁'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toHaveText('这部作品或剧集已不可用。');expect(wallet.pointsBalance).toBe(40);});

test('触屏无Hover、长标题记录、解锁价格与弹窗视觉检查',async({browser,baseURL})=>{const context=await browser.newContext({baseURL,viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});const page=await context.newPage();const wallet=await mock(page,'premium');await page.goto('/play/drama-05');await page.locator('.points-trigger').tap();await expect(page.getByRole('region',{name:'积分账户'})).toBeVisible();await page.locator('.points-trigger').tap();await expect(page.getByRole('region',{name:'积分账户'})).toBeHidden();await page.getByRole('button',{name:'第7集，需8积分解锁',exact:true}).tap();await expect(page.getByRole('dialog')).toContainText('原价：10积分');await expect(page.getByRole('dialog')).toContainText('尊享价：8积分');await page.screenshot({path:'.local/points-unlock-390.png'});await page.getByRole('button',{name:'确认解锁'}).tap();wallet.unlocks[0].contentTitle='这是一个很长的剧集名称，用来验证积分使用详情在手机屏幕中可以换行且不会溢出'.repeat(3);await page.goto('/me/points');await expect(page.getByRole('link',{name:'继续观看'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.local/points-unlocks-390.png',fullPage:true});await page.getByRole('button',{name:'积分明细'}).tap();await page.screenshot({path:'.local/points-transactions-390.png',fullPage:true});await context.close();});

for(const width of [1440,390])test(`当前18+确认、页头与分页流程 ${width}`,async({page})=>{await page.setViewportSize({width,height:844});await mock(page,'premium');await page.goto('/18plus');await page.getByRole('button',{name:'确认并进入',exact:true}).click();await expect(page.locator('#adult-catalog .adult-card').first()).toBeVisible();await expect(page.locator('.points-trigger')).toHaveText('960');await page.locator('.points-trigger').click();await expect(page.getByRole('region',{name:'积分账户'})).toBeVisible();await page.keyboard.press('Escape');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('header nav').getByRole('link',{name:'成人短剧',exact:true}).click();await expect(page.locator('#adult-catalog .adult-card')).toHaveCount(width===390?10:20);await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(page).toHaveURL(/page=2/);await page.locator('header').screenshot({path:`.local/points-adult-header-${width}.png`});});

 test('超大余额在320、820与1440页头不溢出',async({page})=>{const wallet=await mock(page,'premium');wallet.pointsBalance=Number.MAX_SAFE_INTEGER;for(const width of [320,820,1440]){await page.setViewportSize({width,height:844});await page.goto('/me/points');await expect(page.locator('.points-trigger')).toHaveText('9007.2万亿');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.points-trigger').click();await expect(page.getByRole('region').getByText(String(Number.MAX_SAFE_INTEGER),{exact:true})).toBeVisible();}});
