import{test,expect,type Page}from'@playwright/test';
async function start(page:Page,path='/shorts'){await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.emulateMedia({reducedMotion:'reduce'});await page.goto(path);}
async function readyVideo(page:Page){await expect(page.locator('.video-stage')).toHaveAttribute('data-status','ready');await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThan(2);}
async function choose(page:Page,label:string){await page.getByRole('group',{name:label==='古装'?'题材':label==='待公布'||label==='更新中'?'更新状态':'排序',exact:true}).getByRole('button',{name:label,exact:true}).click();}
test('expanded tags combine immediately and survive refresh, back, forward and clear',async({page})=>{
 await start(page);await expect(page.locator('.catalog-tag-filters select')).toHaveCount(0);await expect(page.locator('.tag-options button')).toHaveCount(13);await expect(page.locator('#catalog .drama-card')).toHaveCount(18);await choose(page,'古装');await choose(page,'待公布');await choose(page,'按标题');await expect(page.locator('#catalog .drama-card')).toHaveCount(3);await expect(page).toHaveURL(/genre=.*update=unknown.*sort=title/);await page.reload();for(const label of ['古装','待公布','按标题'])await expect(page.getByRole('button',{name:label,exact:true})).toHaveAttribute('aria-pressed','true');await choose(page,'更新中');await expect(page.locator('.empty-state')).toBeVisible();await page.goBack();await expect(page.locator('#catalog .drama-card')).toHaveCount(3);await page.goForward();await expect(page.locator('.empty-state')).toBeVisible();await page.getByRole('button',{name:'清除条件',exact:true}).click();await expect(page.locator('#catalog .drama-card')).toHaveCount(18);await expect(page).toHaveURL(/\/shorts$/);
});
test('shared filters are fully exposed on all four catalog pages',async({page})=>{for(const path of ['/shorts','/comics','/free','/search?q=月色']){await start(page,path);await expect(page.getByRole('group',{name:'题材',exact:true})).toBeVisible();await expect(page.getByRole('group',{name:'更新状态',exact:true})).toBeVisible();await expect(page.getByRole('group',{name:'排序',exact:true})).toBeVisible();await expect(page.locator('.preview-note')).toHaveCount(0);}});
test('Chinese two-level breadcrumb covers inner pages and protects gated title',async({page})=>{for(const [url,name]of [['/shorts','短剧'],['/comics','漫剧'],['/rankings','排行榜'],['/membership','会员中心'],['/me','我的'],['/me/orders','我的订单'],['/me/privacy','隐私设置'],['/collections','策展片单'],['/collections/everyday-light','都市心事'],['/search','搜索结果'],['/play/drama-08','月色不晚'],['/18plus/play/private-preview-1','访问确认']]){await start(page,url);await expect(page.locator('.breadcrumb')).toHaveText('首页/'+name);await expect(page.locator('.breadcrumb a')).toHaveCount(1);await expect(page.locator('.breadcrumb [aria-current]')).toHaveCount(1);}await expect(page.locator('.adult-context')).toHaveCount(0);});
test('play, pause, seek, sound, rate, fullscreen and cleanup use real media state',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page,'/play/drama-08');await readyVideo(page);const video=page.locator('video');await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.2);await page.getByRole('button',{name:'暂停视频',exact:true}).click();expect(await video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);await page.getByLabel('播放进度',{exact:true}).fill('6');await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(5.8);await page.getByLabel('音量',{exact:true}).fill('0.25');expect(await video.evaluate((v:HTMLVideoElement)=>v.volume)).toBe(.25);expect(await video.evaluate((v:HTMLVideoElement)=>v.muted)).toBe(false);await page.getByRole('button',{name:'静音',exact:true}).click();expect(await video.evaluate((v:HTMLVideoElement)=>v.muted)).toBe(true);await page.getByLabel('播放倍速').selectOption('1.5');expect(await video.evaluate((v:HTMLVideoElement)=>v.playbackRate)).toBe(1.5);await page.getByRole('button',{name:'全屏',exact:true}).click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await page.getByRole('button',{name:'退出全屏',exact:true}).click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(false);await page.getByRole('button',{name:'播放视频',exact:true}).click();await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(false);await page.evaluate(()=>{(window as any).oldVideo=document.querySelector('video');});await page.locator('.breadcrumb a').click();expect(await page.evaluate(()=>(window as any).oldVideo.paused)).toBe(true);expect(await page.evaluate(()=>(window as any).oldVideo.querySelector('source').hasAttribute('src'))).toBe(false);expect(errors).toEqual([]);
});
test('episode buttons, previous/next, range groups and simulated tiers stay synchronized',async({page})=>{
 await start(page,'/play/drama-08');await readyVideo(page);await expect(page.getByRole('button',{name:'上一集',exact:true})).toBeDisabled();await page.evaluate(()=>{(window as any).oldVideo=document.querySelector('video');});await page.getByRole('button',{name:'下一集',exact:true}).click();await readyVideo(page);await expect(page.locator('h1')).toContainText('第2集');expect(await page.locator('video').evaluate((v:HTMLVideoElement)=>v.videoWidth/v.videoHeight)).toBeCloseTo(9/16,2);expect(await page.evaluate(()=>(window as any).oldVideo.paused)).toBe(true);await expect(page.locator('.episode-grid [aria-current]')).toHaveText(/2/);await page.getByRole('button',{name:'上一集',exact:true}).click();await readyVideo(page);expect(await page.locator('video').evaluate((v:HTMLVideoElement)=>v.videoWidth/v.videoHeight)).toBeCloseTo(16/9,2);await page.getByRole('button',{name:'第7集，需悦享会员权益',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('本集需要悦享会员权益');await expect(page.locator('h1')).toContainText('第1集');await page.keyboard.press('Escape');await page.getByLabel('账户权益').selectOption('basic');await page.getByRole('button',{name:'第7集',exact:true}).click();await expect(page.locator('h1')).toContainText('第7集');await page.getByRole('button',{name:'31–36',exact:true}).click();await expect(page.locator('.episode-grid button')).toHaveCount(6);await page.getByRole('button',{name:'第31集，需尊享会员权益',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('高级');await page.keyboard.press('Escape');await page.getByLabel('账户权益').selectOption('premium');await page.getByRole('button',{name:'第36集',exact:true}).click();await expect(page.locator('h1')).toContainText('第36集');await expect(page.getByRole('button',{name:'下一集',exact:true})).toBeDisabled();await page.getByLabel('账户权益').selectOption('free');await expect(page.locator('h1')).toContainText('第1集');await expect(page.getByRole('button',{name:'1–30',exact:true})).toHaveAttribute('aria-pressed','true');
});
test('close player restores source list filters and scroll; direct visits return home',async({page})=>{
 await start(page);await choose(page,'古装');await choose(page,'按标题');const link=page.locator('.drama-card').first();await link.scrollIntoViewIfNeeded();const before=await page.evaluate(()=>scrollY),url=page.url();await link.click();await readyVideo(page);await page.getByRole('button',{name:'返回上一列表',exact:true}).click();await expect(page).toHaveURL(url);await expect(page.getByRole('button',{name:'古装',exact:true})).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.evaluate(()=>scrollY)).toBeCloseTo(before,0);await page.goto('/play/drama-08');await readyVideo(page);await page.getByRole('button',{name:'返回上一列表',exact:true}).click();await expect(page).toHaveURL(/\/#home$/);
});
test('collection toggle, comment notice, plot expansion and copy have actual feedback',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await start(page,'/play/drama-05');await readyVideo(page);await page.getByRole('button',{name:'收藏',exact:true}).click();await expect(page.getByRole('button',{name:'已收藏',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'已收藏',exact:true}).click();await expect(page.getByRole('button',{name:'收藏',exact:true})).toHaveAttribute('aria-pressed','false');await page.getByRole('button',{name:'评论',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('评论功能暂未开放');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'评论',exact:true})).toBeFocused();const expand=page.getByRole('button',{name:'展开',exact:true});if(await expand.count()){await expand.click();await expect(page.getByRole('button',{name:'收起',exact:true})).toHaveAttribute('aria-expanded','true');await page.getByRole('button',{name:'收起',exact:true}).click();}await page.getByRole('button',{name:'复制链接',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'链接已复制'})).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('/play/drama-05');
});
test('loading failure retries successfully without phantom playback',async({page})=>{let fail=true;await page.route('**/media/demo/landscape.mp4',async route=>{await new Promise(r=>setTimeout(r,350));if(fail)await route.fulfill({status:404,body:''});else await route.continue();});await start(page,'/play/drama-08');await expect(page.getByText('正在加载视频…')).toBeVisible();await expect(page.getByRole('heading',{name:'视频暂时无法播放'})).toBeVisible();fail=false;await page.getByRole('button',{name:'重新加载',exact:true}).click();await readyVideo(page);await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.2);});
test('protected demo is available only after explicit test access confirmation',async({page})=>{
 await start(page,'/18plus/play/private-preview-1');await expect(page.locator('.breadcrumb')).toHaveText('首页/访问确认');await expect(page.locator('video')).toHaveCount(0);await page.goto('/__debug');await page.locator('summary').click();await page.getByLabel('地区流程场景').selectOption('allowed');await page.getByRole('navigation',{name:'主导航'}).getByRole('link',{name:'18+专区',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'确认并进入',exact:true}).click();await expect(page.locator('.adult-context')).toBeVisible();await page.locator('.offset-0 a').click();await readyVideo(page);await expect(page.getByRole('button',{name:'复制链接',exact:true})).toHaveCount(0);await expect(page.getByText('私密内容不提供公开分享')).toBeVisible();await page.evaluate(()=>{(window as any).oldVideo=document.querySelector('video');});await page.getByRole('button',{name:'退出18+专区'}).click();await expect(page.locator('video')).toHaveCount(0);expect(await page.evaluate(()=>(window as any).oldVideo.paused)).toBe(true);await page.goBack();await expect(page.locator('.breadcrumb')).toHaveText('首页/访问确认');
});
for(const [width,height]of [[320,812],[390,844],[768,1024],[1280,720],[1920,1080]])test(`layout, exposed filters and video geometry ${width}`,async({page})=>{await page.setViewportSize({width,height});await start(page);for(const row of await page.locator('.tag-options').all())await expect(row).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.goto('/play/drama-08');await readyVideo(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('video')).toHaveCSS('object-fit','contain');const left=await page.locator('.watch-media').boundingBox(),right=await page.locator('.watch-info').boundingBox();if(width>760){expect(Math.abs(left!.y-right!.y)).toBeLessThan(1);expect(left!.width/right!.width).toBeCloseTo(1.5,1);}else expect(right!.y).toBeGreaterThan(left!.y+left!.height-1);});

test('touch controls preserve video preferences across episode switches',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,baseURL:'http://localhost:5173'});const page=await context.newPage();await start(page,'/play/drama-08');await readyVideo(page);await page.getByRole('button',{name:'暂停视频',exact:true}).tap();expect(await page.locator('video').evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);await page.getByLabel('音量',{exact:true}).fill('0.3');await page.getByLabel('播放倍速').selectOption('1.25');await page.getByRole('button',{name:'下一集',exact:true}).tap();await readyVideo(page);expect(await page.locator('video').evaluate((v:HTMLVideoElement)=>[v.volume,v.muted,v.playbackRate])).toEqual([.3,false,1.25]);await page.getByRole('button',{name:'第3集',exact:true}).tap();await readyVideo(page);await expect(page.locator('h1')).toContainText('第3集');await context.close();});
test('real progress dragging and buffering state remain operable',async({page})=>{await start(page,'/play/drama-08');await readyVideo(page);await page.getByRole('button',{name:'暂停视频',exact:true}).click();const slider=await page.getByLabel('播放进度',{exact:true}).boundingBox();await page.mouse.move(slider!.x+slider!.width*.2,slider!.y+slider!.height/2);await page.mouse.down();await page.mouse.move(slider!.x+slider!.width*.6,slider!.y+slider!.height/2,{steps:12});await page.mouse.up();await expect.poll(()=>page.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(6);await page.locator('video').dispatchEvent('waiting');await expect(page.getByText('正在缓冲…')).toBeVisible();await page.locator('video').dispatchEvent('canplay');await expect(page.getByText('正在缓冲…')).toHaveCount(0);});

test('video picture area is reserved above controls in wide and narrow players',async({page})=>{for(const width of [1280,390,320]){await page.setViewportSize({width,height:844});await start(page,'/play/drama-08');await readyVideo(page);for(let i=0;i<2;i++){if(i){await page.getByRole('button',{name:'下一集',exact:true}).click();await readyVideo(page);}const video=await page.locator('video').boundingBox(),controls=await page.locator('.player-controls').boundingBox();expect(video!.y+video!.height).toBeLessThanOrEqual(controls!.y+1);}}});
