import {test,expect} from '@playwright/test';
import {previewCatalog} from '../src/data/previewCatalog';
const firstFive=['drama-05','drama-08','drama-03','drama-17','drama-04'];
async function start(page:any){await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#home');await expect(page.locator('.hero-poster')).toHaveCount(5);}
test('restored snapshot uses the original covers, order and matching detail data',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await start(page);
 expect(previewCatalog).toHaveLength(18);expect(previewCatalog.slice(0,5).map(c=>c.id)).toEqual(firstFive);
 await expect(page.locator('#popular .drama-card')).toHaveCount(12);await expect(page.locator('#latest .drama-card')).toHaveCount(6);await expect(page.locator('#popular .preview-badge')).toHaveCount(0);
 for(const item of previewCatalog){expect((await page.request.get(item.cover)).status()).toBe(200);expect((await page.request.get(item.largeCover)).status()).toBe(200);}
 await page.getByLabel('搜索精选内容').fill('月色');await expect(page.locator('#popular .drama-card')).toHaveCount(1);await page.locator('#popular .drama-card').click();await expect(page).toHaveURL(/\/play\/drama-08$/);await expect(page.locator('h1')).toContainText('月色不晚');await expect(page.locator('video')).toHaveCount(1);await page.goBack();await expect(page.getByLabel('搜索精选内容')).toHaveValue('月色');await expect(page.locator('#popular .drama-card')).toHaveCount(1);
 await page.getByRole('button',{name:'清空搜索',exact:true}).click();await expect(page.locator('#latest .drama-card')).toHaveCount(6);await expect(page.getByLabel('搜索精选内容')).toHaveValue('');expect(errors).toEqual([]);
});
for(const [width,height]of [[1280,720],[390,844],[320,812]])test(`restored layout ${width}`,async({page})=>{await page.setViewportSize({width,height});await start(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.offset-0 img')).toHaveAttribute('src','/assets/covers/drama-05-large.webp');await expect.poll(()=>page.locator('.hero-poster:visible img').evaluateAll(images=>images.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true);await page.screenshot({path:`docs/restored-covers/home-${width}.png`});await page.locator('#popular').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.waitForTimeout(250);await expect.poll(()=>page.locator('#popular img').evaluateAll(images=>images.filter(img=>{const r=img.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight;}).every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true);if(width<=390)expect(await page.locator('#popular .drama-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length)).toBe(2);await page.screenshot({path:`docs/restored-covers/popular-${width}.png`});await page.getByRole('button',{name:'登录 / 注册',exact:true}).click();await page.keyboard.press('Escape');await expect(page.locator('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'登录 / 注册',exact:true})).toBeFocused();});
test('all five restored carousel states retain immutable outer hover geometry',async({page})=>{
 await page.setViewportSize({width:1280,height:720});await start(page);
 const shape=async(slot:number)=>page.locator(`[data-slot="${slot}"]`).evaluate(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el),img=getComputedStyle(el.querySelector('img')!);return [r.x,r.y,r.width,r.height,s.zIndex,s.filter,img.transform,img.filter];});
 for(let i=0;i<5;i++){await page.locator('.carousel-dots button').nth(i).click();await expect(page.locator('.offset-0')).toHaveAttribute('data-drama-id',firstFive[i]);for(const slot of [-2,2]){await page.mouse.move(10,10);const before=await shape(slot);const point=await page.locator(`[data-slot="${slot}"]`).evaluate(el=>{const r=el.getBoundingClientRect();for(let x=Math.max(5,r.left+5);x<Math.min(innerWidth-5,r.right);x+=5){const y=r.top+r.height*.5;if(document.elementFromPoint(x,y)?.closest('.hero-poster')===el)return{x,y};}return null;});expect(point).not.toBeNull();await page.mouse.move(point!.x,point!.y);await page.waitForTimeout(250);expect(await shape(slot)).toEqual(before);}}
});
