import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const sizes=[[320,812],[390,844],[768,1024],[1280,720],[1920,1080]];
for(const [width,height] of sizes)test(`stable filters, compact clear and equal player ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));await page.goto('/#home');await expect(page.locator('#popular .drama-card')).toHaveCount(12);
 await page.locator('#popular').evaluate(e=>window.scrollTo({top:scrollY+e.getBoundingClientRect().top-Number.parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--header-height'))-25,behavior:'instant'}));
 await page.waitForTimeout(200);const baseline=await page.evaluate(()=>scrollY);
 await page.evaluate(()=>{(window as any).positions=[];(window as any).sample=setInterval(()=>(window as any).positions.push(scrollY),10);});
 for(const genre of ['古装','奇幻','悬疑','都市情感','全部']){await page.locator('#browse').getByRole('button',{name:genre,exact:true}).click();await page.waitForTimeout(100);await expect(page.locator('#popular-heading')).toHaveText('热门推荐');}
 const positions=await page.evaluate(()=>{clearInterval((window as any).sample);return (window as any).positions as number[];});expect(Math.max(...positions)-Math.min(...positions)).toBeLessThan(2);expect(await page.evaluate(()=>scrollY)).toBeCloseTo(baseline,0);
 await expect(page.locator('#latest .drama-card')).toHaveCount(6);await expect(page.locator('.home-section-nav,.section-count,.filter-result,.intro-replay')).toHaveCount(0);await expect(page.getByRole('button',{name:/重置筛选|重新筛选/})).toHaveCount(0);
 fs.mkdirSync('docs/ui-cleanup',{recursive:true});await page.screenshot({path:`docs/ui-cleanup/home-${width}.png`});
 await page.goto('/shorts');await expect(page.locator('#catalog .drama-card')).toHaveCount(18);const box=await page.locator('.catalog-tag-filters').boundingBox(),clear=await page.getByRole('button',{name:'清除条件',exact:true}).boundingBox();expect(clear!.y-box!.y).toBeLessThan(24);expect(box!.x+box!.width-clear!.x-clear!.width).toBeLessThan(28);
 for(const tag of await page.locator('.tag-options button').all()){const b=await tag.boundingBox();expect(b!.x+b!.width<=clear!.x||b!.y>=clear!.y+clear!.height||b!.x>=clear!.x+clear!.width).toBe(true);}
 await page.getByRole('button',{name:'古装',exact:true}).click();const before=await page.evaluate(()=>scrollY);await page.getByRole('button',{name:'清除条件',exact:true}).click();expect(await page.evaluate(()=>scrollY)).toBeCloseTo(before,0);await page.screenshot({path:`docs/ui-cleanup/filters-${width}.png`});
 await page.goto('/play/drama-08');await expect(page.locator('.video-stage')).toHaveAttribute('data-status','ready');await page.locator('video').evaluate((v:HTMLVideoElement)=>{v.pause();v.currentTime=2;});await page.waitForTimeout(200);
 const left=await page.locator('.video-stage').boundingBox(),right=await page.locator('.watch-info').boundingBox();if(width>760){expect(Math.abs(left!.y-right!.y)).toBeLessThan(1);expect(Math.abs(left!.y+left!.height-right!.y-right!.height)).toBeLessThan(1);await page.locator('.watch-info').evaluate(e=>e.scrollTop=e.scrollHeight);await expect(page.getByLabel('账户权益',{exact:true})).toBeVisible();await page.locator('.watch-info').evaluate(e=>e.scrollTop=0);}
 await expect(page.locator('video')).toHaveCSS('object-fit','contain');await expect(page.locator('.demo-source-note')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`docs/ui-cleanup/player-${width}.png`,fullPage:width<761});
});
test('customer pages contain no redundant demo copy and report no console errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.addInitScript(()=>sessionStorage.setItem('aiai:intro-seen','yes'));for(const url of ['/#home','/shorts','/comics','/free','/search?q=月色','/search?q=xxxxxxxx','/collections','/collections/everyday-light','/rankings','/membership','/me','/me/privacy','/me/orders','/18plus','/play/drama-08']){await page.goto(url);await page.waitForTimeout(220);expect(await page.locator('body').innerText()).not.toMatch(/演示|预览|占位|仅供测试|仅测试|不代表本作品|待完善|展示编排|\d+\s*部(?:结果|短剧|符合)/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}expect(errors).toEqual([]);});
