import{Breadcrumb}from'../components/Breadcrumb';
import{useEffect,useRef,useState,type ReactNode}from'react';import{ShieldCheck,ArrowLeft,LockKeyhole}from'lucide-react';
import{accessService,type RegionState}from'../services/access';import{useAccess,useContents,useCampaigns}from'../services/hooks';import{useRouter,Link}from'../navigation/Router';import{track}from'../services/analytics';import{EmptyState,LoadingState,PageHeading,ErrorState}from'../components/content/PageParts';import{DramaGrid}from'../components/DramaGrid';import{Carousel}from'../components/Carousel';import{useReducedMotion}from'../hooks/useReducedMotion';import{filterInZone}from'../services/rules';import{useRecords,records}from'../state/records';import{DialogShell}from'../components/DialogShell';import{contentLabel}from'../data/contentLabels';import{contentHref}from'../navigation/Router';import type{AccessContext}from'../types/content';
export function AdultBoundary({children}:{children:ReactNode}){
 const{route,navigate}=useRouter(),access=useAccess();const[verified,setVerified]=useState(false),[checking,setChecking]=useState(true),[age,setAge]=useState(false),[region,setRegion]=useState<RegionState>('checking'),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);const action=useRef<AbortController|null>(null);const gate=useRef(crypto.randomUUID());const finished=useRef(false);useEffect(()=>()=>action.current?.abort(),[]);
 useEffect(()=>{const abort=new AbortController();setVerified(false);setChecking(true);setAge(false);finished.current=false;accessService.verify(abort.signal).then(valid=>{if(abort.signal.aborted)return;setVerified(valid);setChecking(false);if(!valid){track({name:'age_gate_view',zone:'adult',gateId:gate.current},`gate-view:${gate.current}`);setRegion('checking');void accessService.checkRegion(abort.signal).then(setRegion).catch(()=>{});}}).catch(()=>{});return()=>{abort.abort();document.documentElement.style.removeProperty('--current-ambience');};},[route.path,route.search,access.revision,attempt]);
 const exit=()=>{action.current?.abort();if(!finished.current){finished.current=true;track({name:'age_gate_exit',zone:'adult',gateId:gate.current},`gate-exit:${gate.current}`);}navigate('/#home');};
 useEffect(()=>{if(verified)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();exit();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[verified,route.key]);
 const enter=async()=>{if(!age||region!=='allowed'||busy)return;setBusy(true);action.current?.abort();const controller=new AbortController();action.current=controller;const accepted=await accessService.enter(age,true,controller.signal).catch(()=>false);if(controller.signal.aborted)return;setBusy(false);if(accepted){finished.current=true;track({name:'age_gate_pass',zone:'adult',gateId:gate.current},`gate-pass:${gate.current}`);}else{setRegion('unknown');track({name:'age_gate_denied',zone:'adult',gateId:gate.current});}};
 if(checking)return <main className="container page neutral-gate"><LoadingState label="正在检查访问条件…"/></main>;
 if(verified&&accessService.isGranted())return <div className="adult-context"><div className="adult-bar container"><span><LockKeyhole size={15}/>18+专区 · 私密浏览</span><button className="text-button" onClick={()=>{accessService.revoke();navigate('/#home');}}>退出18+专区</button></div>{children}</div>;
 const status={checking:'正在检查地区访问条件…',allowed:'地区访问检查通过',denied:'此访问地区暂不开放',unknown:'目前无法确认访问地区',error:'地区检查未完成，请重试'}[region];
 return <main className="container page gate-page"><div className="gate-card surface-panel"><span className="gate-symbol"><ShieldCheck size={38}/></span><Breadcrumb neutral/><h1>进入18+专区前</h1><p>此专区仅限已满 18 周岁的用户。请确认年龄，并完成地区访问条件检查。</p><div className={`region-status ${region}`} role="status"><strong>{status}</strong><span>{region==='allowed'?'请确认年龄后进入。':'地区未确认、检查失败或不允许时，均无法进入。'}</span></div><label className="age-confirm"><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/><span>我确认已满 18 周岁，并主动选择进入此专区。</span></label><button className="primary-button" disabled={!age||region!=='allowed'||busy} onClick={()=>void enter()}>{busy?'正在确认…':'确认并进入'}</button><button className="secondary-button" onClick={exit}><ArrowLeft size={16}/>返回首页</button>{region!=='allowed'&&region!=='checking'&&<button className="text-button" onClick={()=>setAttempt(n=>n+1)}>重试地区检查</button>}</div></main>;
}
export const adultContext:AccessContext={zone:'adult',channel:'preview',adultGranted:true,region:null,tier:'free',sessionVerified:false};
export function AdultPage(){const{route}=useRouter();const campaigns=useCampaigns(adultContext);const data=useContents(adultContext),reduced=useReducedMotion();const tab=route.params.get('tab')||'shorts';const items=data.items.filter(item=>tab==='shorts'?item.format==='live_action_drama':tab==='comics'?item.format==='motion_comic':tab==='original'?item.original:true);
 return <main><div className="container page adult-heading"><PageHeading eyebrow="18+ · PRIVATE SPACE" title="属于你的私密浏览空间" description=""/><nav className="adult-tabs" aria-label="专区分类">{[['shorts','成人短剧'],['comics','成人漫剧'],['original','原创'],['latest','最新'],['popular','热门']].map(([id,label])=><Link key={id} href={`/18plus?tab=${id}`} aria-current={tab===id?'page':undefined}>{label}</Link>)}</nav><div className="private-links"><Link href="/18plus/wishlist">私密愿望榜</Link><Link href="/18plus/search">专区搜索</Link><Link href="/membership?context=adult">会员权益</Link></div></div>{data.loading?<LoadingState/>:data.error?<ErrorState message={data.error} retry={data.retry}/>:<><Carousel items={data.items} reduced={reduced} blocked={false}/><div className="container page"><DramaGrid id="adult-catalog" title={tab==='original'?'原创作品':'专区内容'} subtitle="" items={items}/><div className="campaign-grid">{campaigns.map(c=><Link key={c.id} className="surface-panel" href={c.target}><h2>{c.title}</h2><p>{c.description}</p></Link>)}</div></div></>}</main>;
}
export function AdultSearch(){const data=useContents(adultContext),[query,setQuery]=useState(''),[committed,setCommitted]=useState(''),[enabled,setEnabled]=useState(false);const composing=useRef(false);const found=filterInZone(data.items,adultContext,committed);
 return <main className="container page"><PageHeading title="专区搜索" description="仅搜索当前专区，查询不会写入地址或公共搜索历史。"/>{!enabled?<div className="surface-panel"><p>主动开启后，本次页面的查询仅保留在内存中，离开即清除。</p><button className="primary-button" onClick={()=>setEnabled(true)}>开启专区搜索</button></div>:<><form className="private-search-form" onSubmit={e=>{e.preventDefault();if(composing.current)return;setCommitted(query.trim());track({name:'search_submit',zone:'adult'});}}><label>专区关键词<input value={query} onChange={e=>setQuery(e.target.value)} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}} onKeyDown={e=>{if(e.key==='Enter'&&(composing.current||e.nativeEvent.isComposing))e.preventDefault();}}/></label><button className="primary-button">搜索</button><button className="secondary-button" type="button" onClick={()=>{setQuery('');setCommitted('');}}>清空</button></form>{data.loading?<LoadingState/>:data.error?<ErrorState message={data.error} retry={data.retry}/>:found.length?<DramaGrid id="private-results" title="搜索结果" subtitle="仅在当前专区内呈现" items={found} results/>:<EmptyState title="没有找到相关内容" onReset={()=>{setQuery('');setCommitted('');}}/>}</>}</main>;
}
export function WishlistPage(){const state=useRecords(),data=useContents(adultContext),[removeId,setRemoveId]=useState<string|null>(null);const items=data.items.filter(c=>state.wishlist.includes(c.id));return <main className="container page"><PageHeading title="私密愿望榜" description="默认私密，不提供公开分享。退出资格后，本地临时记录会被清除。"/>{data.loading?<LoadingState/>:!items.length?<EmptyState title="愿望榜还是空的" description="在专区详情中，把感兴趣的作品加入愿望榜。"><Link className="primary-button" href="/18plus">发现专区内容</Link></EmptyState>:<div className="private-records">{items.map(c=><div className="surface-panel private-record" key={c.id}><img src={c.thumbnail} alt="封面"/><div><h2>{c.title}</h2><Link className="text-button" href={contentHref(c)}>{contentLabel(c)}</Link><button className="text-button" onClick={()=>setRemoveId(c.id)}>移出愿望榜</button><button className="secondary-button" disabled={state.reservations.includes(c.id)} onClick={()=>records.reserve(c.id)}>{state.reservations.includes(c.id)?'已记录本地预约':'记录本地预约'}</button><small>不会发送邮件、通知或创建账号预约。</small></div></div>)}</div>}<section className="surface-panel private-history"><h2>私密观看历史</h2>{state.privacy.hideAdult?<p>历史已隐藏。隐藏不会删除记录，可在隐私设置中调整。</p>:<p>暂无已核实的观看记录。浏览详情不会被标记为已观看。</p>}<Link className="text-button" href="/me/privacy">管理隐私设置</Link></section>{removeId&&<DialogShell title="移出私密愿望榜？" onClose={()=>setRemoveId(null)}><p>仅移除本地临时关注和对应预约，不涉及服务器数据。</p><button className="primary-button" onClick={()=>{records.toggleWishlist(removeId);setRemoveId(null);}}>确认移出</button></DialogShell>}</main>;}
