import{CatalogFilters,FilterTags}from'../components/content/CatalogFilters';
import{useReadyScroll}from'../navigation/useReadyScroll';
﻿import{useMemo}from'react';import{ArrowUpRight,ChevronLeft}from'lucide-react';
import{DramaGrid}from'../components/DramaGrid';import{PageHeading,PreviewNote,EmptyState,LoadingState,ErrorState}from'../components/content/PageParts';import{useContents}from'../services/hooks';import{greenContext}from'../services/content';import{filterInZone}from'../services/rules';import{genres}from'../data/dramas';import{collections}from'../data/previewCatalog';import{Link,useRouter}from'../navigation/Router';
export function CatalogPage({kind}:{kind:'shorts'|'comics'|'free'|'search'}){
 const{route,navigate}=useRouter();const data=useContents();useReadyScroll(!data.loading);const genre=route.params.get('genre')||'全部',update=route.params.get('update')||'all',sort=route.params.get('sort')||'curated',query=kind==='search'?route.params.get('q')||'':'';
 const items=useMemo(()=>{let list=filterInZone(data.items,greenContext,query,genre);if(kind==='shorts')list=list.filter(c=>c.format==='live_action_drama');if(kind==='comics')list=list.filter(c=>c.format==='motion_comic');if(kind==='free')list=list.filter(c=>c.access_tier==='free'&&!!c.free_scope);if(update!=='all')list=list.filter(c=>c.update_status===update);if(sort==='title')list=[...list].sort((a,b)=>a.title.localeCompare(b.title,'zh-CN'));return list;},[data.items,genre,query,kind,sort,update]);
 const change=(key:string,value:string)=>{const params=new URLSearchParams(route.search);if(value==='all'||value==='全部'||value==='curated')params.delete(key);else params.set(key,value);params.delete('page');navigate(route.path+(params.size?'?'+params:''),{replace:false,preserveScroll:true});};
 const reset=()=>navigate(kind==='search'?'/search':'/'+kind,{preserveScroll:true});
 const titles={shorts:'精选短剧',comics:'漫剧新视野',free:'免费专区',search:'搜索结果'};
 return <main className="container page"><PageHeading title={titles[kind]} description={kind==='search'?query?`与「${query}」有关的精选内容`:'输入剧名，发现下一部好故事':kind==='free'?'免费范围清晰可见，慢慢发现你的下一部好故事。':'循着喜欢的题材，发现属于你的故事。'}/><PreviewNote/>
 <CatalogFilters genre={genre} update={update} sort={sort} onChange={change} onReset={reset}/>
 {data.loading?<LoadingState/>:data.error?<ErrorState message={data.error} retry={data.retry}/>:items.length?<DramaGrid id="catalog" title={kind==='search'?'找到这些故事':'全部作品'}  items={items} results={kind==='search'}/>:<EmptyState title="还没找到这部故事" description="可以调整题材、更新状态，或换个关键词。" onReset={reset}/>}</main>;
}
export function CollectionsPage({id}:{id?:string}){
 const data=useContents(),collection=collections.find(c=>c.id===id);useReadyScroll(!data.loading);
 if(id&&!collection)return <main className="container page"><EmptyState title="片单暂不可用"><Link href="/collections" className="primary-button">返回片单</Link></EmptyState></main>;
 if(collection){const items=collection.content_ids.map(id=>data.items.find(c=>c.id===id)).filter((item):item is NonNullable<typeof item>=>!!item);return <main className="container page"><Link className="back-link" href="/collections"><ChevronLeft size={18}/>全部片单</Link><PageHeading title={collection.name} description={collection.description}/><div className="collection-intro surface-panel"><img src={collection.cover} alt="片单封面"/><div><span className="eyebrow">主题片单</span><h2>{collection.theme}</h2><p>更新于 {collection.updated_at}</p></div></div>{data.loading?<LoadingState/>:<DramaGrid id="collection-items" title="片单顺序" subtitle="按照策展顺序呈现" items={items}/>}</main>;}
 return <main className="container page"><PageHeading title="沿着主题，遇见好故事" description="每一份片单，都有一条属于它的观看线索。"/><PreviewNote/><div className="collection-grid">{collections.map(c=><Link key={c.id} href={`/collections/${c.id}`} className="collection-card surface-panel"><img src={c.cover} alt={c.name+'封面'}/><div><span className="eyebrow">主题片单</span><h2>{c.name}</h2><p>{c.description}</p><span className="text-link">探索片单 <ArrowUpRight size={16}/></span></div></Link>)}</div></main>;
}
export function RankingsPage(){const{route,navigate}=useRouter();const period=route.params.get('period')==='week'?'week':'day',genre=route.params.get('genre')||'全部';const change=(key:string,value:string)=>{const params=new URLSearchParams(route.search);params.set(key,value);navigate('/rankings?'+params,{preserveScroll:true});};return <main className="container page"><PageHeading eyebrow="AIAI · RANKINGS" title="值得发现的好故事" description="排行榜独立统计精选内容，帮你找到下一部值得关注的故事。"/><div className="rank-controls"><div className="segmented" aria-label="榜单周期"><button aria-pressed={period==='day'} onClick={()=>change('period','day')}>日榜</button><button aria-pressed={period==='week'} onClick={()=>change('period','week')}>周榜</button></div><FilterTags label="题材" options={genres.map(g=>[g,g])} value={genre} onChange={v=>change('genre',v)}/></div><EmptyState title="暂无榜单数据" description="暂时没有可展示的排名。"/></main>;}
