import {extraViewingDaysFor} from '../services/festivalModel';
import {useFestivalPhase} from '../hooks/useFestivalPhase';
import {createHttpBackend,type OrderDTO} from '../services/backend';
import {useEffect,useState,useSyncExternalStore} from 'react';
import {CreditCard,Clock3,ReceiptText} from 'lucide-react';
import {PageHeading,EmptyState} from '../components/content/PageParts';
import {Link,useRouter} from '../navigation/Router';
import {accountService,type PlanId} from '../services/membership';
import {AccountNav} from '../components/AccountNav';
const money=(yuan:number)=>`¥${yuan.toFixed(2)}`;
type ViewQuote={id:PlanId;title:string;total:number;tier:'basic'|'premium';durationDays:number|null;validity:'fixed'|'permanent'};

export function CheckoutPage(){
 const phase=useFestivalPhase(),{route}=useRouter(),account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),planId=route.params.get('plan') as PlanId|null,returnTo=route.params.get('returnTo');
 const [plan,setPlan]=useState<ViewQuote|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!planId){setLoading(false);return;}let cancelled=false;setLoading(true);fetch('/api/v1/membership/view-plans/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId})}).then(async response=>{if(!response.ok)throw Error('quote_unavailable');return response.json() as Promise<ViewQuote>}).then(value=>{if(!cancelled)setPlan(value)}).catch(()=>{if(!cancelled)setPlan(null)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[planId]);
 if(loading)return <main className="container page"><p role="status">正在获取服务端报价…</p></main>;
 if(!plan)return <main className="container page"><EmptyState title="没有找到这个会员方案" description="方案可能已经调整，请重新选择。"><Link className="primary-button" href="/membership">返回会员中心</Link></EmptyState></main>;
 const checkoutPath=`/checkout?plan=${plan.id}${returnTo?`&returnTo=${encodeURIComponent(returnTo)}`:''}`;
 return <main className="container page checkout-page"><PageHeading title="确认订单" description="请核对会员方案、有效期和应付金额。"/><div className="checkout-layout"><section className="surface-panel checkout-summary"><h2>{plan.title}</h2><dl><div><dt>会员等级</dt><dd>{plan.tier==='basic'?'悦享会员':'尊享会员'}</dd></div><div><dt>有效期限</dt><dd>{plan.validity==='permanent'?'永久有效':`${plan.durationDays} 天`}</dd></div><div><dt>自动续费</dt><dd>不自动续费</dd></div><div><dt>应付总额</dt><dd className="checkout-total">{money(plan.total/100)}</dd></div></dl>{phase==='active'&&extraViewingDaysFor(plan.id)>0&&<div className="purchase-festival-bonus"><span>双节活动加赠</span><strong>{extraViewingDaysFor(plan.id)} 天畅看</strong><small>活动期内支付成功后计入会员有效期，每笔均享</small></div>}<ul className="checkout-benefits"><li>会员期内 VIP 剧集畅看，不扣永久积分</li><li>18+ 内容仍需确认年满18周岁</li></ul></section><aside className="surface-panel checkout-actions"><CreditCard/><h2>选择支付方式</h2><label className="payment-option is-disabled"><input type="radio" disabled/>在线支付 <span>暂不可用</span></label><p className="payment-unavailable">支付服务正在准备中，目前无法完成购买。</p><label className="terms-check"><input type="checkbox" disabled/>我已阅读<Link href="/membership-guide">会员说明</Link>和<Link href="/terms">服务协议</Link></label>{account.status==='guest'?<Link className="primary-button" href={`/account/login?returnTo=${encodeURIComponent(checkoutPath)}`}>登录后继续</Link>:<button className="primary-button" disabled>暂不可购买</button>}<Link className="secondary-button" href="/membership">返回会员中心</Link></aside></div></main>;
}
export function OrderDetailPage({id}:{id:string}){
 const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),[order,setOrder]=useState<OrderDTO|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{setOrder(null);if(account.status==='guest'){setLoading(false);return;}const controller=new AbortController();setLoading(true);createHttpBackend(()=>'').order(id,controller.signal).then(value=>{if(!controller.signal.aborted)setOrder(value)}).catch(()=>{}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[id,account.userId]);
 if(account.status==='guest')return <main className="container page"><AccountNav/><EmptyState title="登录后查看订单" description="订单只对账号本人可见。"><Link className="primary-button" href={'/account/login?returnTo='+encodeURIComponent('/me/orders/'+id)}>登录</Link></EmptyState></main>;
 return <main className="container page"><AccountNav/><PageHeading title="订单详情" description="查看支付状态和会员权益。"/>{loading?<p role="status">正在加载订单…</p>:order?<section className="surface-panel"><h2>会员订单</h2><p>订单号：{order.id}</p><p>金额：{money(order.total/100)}</p><p>状态：{({pending:'待支付',processing:'处理中',paid:'已支付',closed:'已关闭',refunding:'退款中',refunded:'已退款'})[order.status]}</p>{order.validity&&<p>权益：{order.validity==='permanent'?'永久有效':`${order.durationDays} 天 · 至 ${order.entitlementExpiresAt?new Date(order.entitlementExpiresAt).toLocaleDateString('zh-CN'):'以权益记录为准'}`}</p>}{order.paidAt&&<p>支付成功时间：{new Date(order.paidAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>}{!!order.extraViewingDays&&<div className="purchase-festival-bonus"><span>双节活动赠送观看天数</span><strong>+{order.extraViewingDays} 天</strong><small>{order.status==='refunded'?'退款后已撤回赠送天数':'已计入会员有效期'}</small></div>}<Link className="secondary-button" href="/membership">查看会员权益</Link></section>:<EmptyState title="暂时无法加载订单" description="订单服务当前不可用，请稍后再试。"><Link className="secondary-button" href="/me/orders">返回我的订单</Link></EmptyState>}</main>;
}
export function PaymentResultPage(){return <main className="container page narrow-page"><PageHeading title="支付结果" description="订单结果以订单服务记录为准。"/><section className="surface-panel result-card"><Clock3/><h2>正在核实订单</h2><p>请以订单详情中的支付和权益状态为准。</p><Link className="primary-button" href="/me/orders"><ReceiptText/>查看我的订单</Link></section></main>}
