import {festivalRewardNames,rechargeBonusFor} from '../services/festivalModel';
import {useFestivalPhase} from '../hooks/useFestivalPhase';
import {createHttpBackend,type OrderDTO} from '../services/backend';
import{useEffect,useState,useSyncExternalStore}from'react';
import{CreditCard,Clock3,ReceiptText}from'lucide-react';
import{PageHeading,EmptyState}from'../components/content/PageParts';import{Link,useRouter}from'../navigation/Router';import{accountService,plans,type PlanId}from'../services/membership';import{AccountNav}from'../components/AccountNav';
const money=(yuan:number)=>`¥${yuan.toFixed(2)}`;
export function CheckoutPage(){const phase=useFestivalPhase();const{route}=useRouter(),account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),planId=route.params.get('plan') as PlanId|null,plan=plans.find(item=>item.id===planId),returnTo=route.params.get('returnTo');if(!plan)return <main className="container page"><EmptyState title="没有找到这个会员方案" description="方案可能已经调整，请重新选择。"><Link className="primary-button" href="/membership">返回会员中心</Link></EmptyState></main>;const checkoutPath=`/checkout?plan=${plan.id}${returnTo?`&returnTo=${encodeURIComponent(returnTo)}`:''}`;return <main className="container page checkout-page"><PageHeading title="确认订单" description="请核对会员方案、有效期和应付金额。"/><div className="checkout-layout"><section className="surface-panel checkout-summary"><h2>{plan.title}</h2><dl><div><dt>会员等级</dt><dd>{plan.tier==='basic'?'悦享会员':'尊享会员'}</dd></div><div><dt>有效期限</dt><dd>{plan.duration}</dd></div><div><dt>自动续费</dt><dd>不自动续费</dd></div><div><dt>应付总额</dt><dd className="checkout-total">{money(plan.prices.A)}</dd></div></dl>{phase==='active'&&rechargeBonusFor(plan.id==='basic-month'?'joy-month':plan.id)>0&&<div className="purchase-festival-bonus"><span>双节活动加赠</span><strong>{rechargeBonusFor(plan.id==='basic-month'?'joy-month':plan.id)}积分</strong><small>活动期内支付成功后到账，每笔均享</small></div>}<ul className="checkout-benefits">{plan.benefits.map(item=><li key={item}>{item}</li>)}</ul></section><aside className="surface-panel checkout-actions"><CreditCard/><h2>选择支付方式</h2><label className="payment-option is-disabled"><input type="radio" disabled/>在线支付 <span>暂不可用</span></label><p className="payment-unavailable">支付服务正在准备中，目前无法完成购买。你的方案选择已经保留，可以稍后再试。</p><label className="terms-check"><input type="checkbox" disabled/>我已阅读<Link href="/membership-guide">会员说明</Link>和<Link href="/terms">服务协议</Link></label>{account.status==='guest'?<Link className="primary-button" href={`/account/login?returnTo=${encodeURIComponent(checkoutPath)}`}>登录后继续</Link>:<button className="primary-button" disabled>暂不可购买</button>}<Link className="secondary-button" href="/membership">返回会员中心</Link></aside></div></main>}
export function OrderDetailPage({id}:{id:string}){
 const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),[order,setOrder]=useState<OrderDTO|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{setOrder(null);if(account.status==='guest'){setLoading(false);return;}const controller=new AbortController();setLoading(true);createHttpBackend(()=>'').order(id,controller.signal).then(value=>{if(!controller.signal.aborted)setOrder(value);}).catch(()=>{}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[id,account.userId]);
 if(account.status==='guest')return <main className="container page"><AccountNav/><EmptyState title="登录后查看订单" description="订单只对账号本人可见。"><Link className="primary-button" href={'/account/login?returnTo='+encodeURIComponent('/me/orders/'+id)}>登录</Link></EmptyState></main>;
 return <main className="container page"><AccountNav/><PageHeading title="订单详情" description="查看支付状态和会员权益。"/>{loading?<p role="status">正在加载订单…</p>:order?<section className="surface-panel"><h2>会员订单</h2><p>订单号：{order.id}</p><p>金额：{money(order.total/100)}</p><p>状态：{({pending:'待支付',processing:'处理中',paid:'已支付',closed:'已关闭',refunding:'退款中',refunded:'已退款'})[order.status]}</p>{order.paidAt&&<p>支付成功时间：{new Date(order.paidAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</p>}{order.festivalRewards?.map(reward=><div key={reward.id} className="purchase-festival-bonus"><span>{festivalRewardNames[reward.kind]}</span><strong>{reward.amount>=0?'+':''}{reward.amount}积分</strong><small>奖励ID：{reward.id}</small>{reward.reversalStatus==='insufficient_balance'&&<small>余额不足，尚有{reward.unrecoveredAmount}积分待回收</small>}</div>)}<Link className="secondary-button" href="/me/points?tab=transactions">查看积分明细</Link></section>:<EmptyState title="暂时无法加载订单" description="订单服务当前不可用，请稍后再试。"><Link className="secondary-button" href="/me/orders">返回我的订单</Link></EmptyState>}</main>;
}
export function PaymentResultPage(){return <main className="container page narrow-page"><PageHeading title="支付结果" description="订单结果以订单服务记录为准。"/><section className="surface-panel result-card"><Clock3/><h2>正在核实订单</h2><p>请以订单详情中的支付和权益状态为准。</p><Link className="primary-button" href="/me/orders"><ReceiptText/>查看我的订单</Link></section></main>}
