import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowRight,CalendarDays,Check,Clock3,Coins,Crown,ReceiptText,ShieldCheck,Sparkles} from 'lucide-react';
import {accountService,type Account} from '../services/membership';
import {pointsService,pointsError,usePoints} from '../services/points';
import {meService,meError,useMeOverview} from '../services/me';
import {festivalService} from '../services/festival';
import {useFestivalPhase} from '../hooks/useFestivalPhase';
import {extraViewingDaysFor} from '../services/festivalModel';
import {permanentCreditsOffer} from '../services/pointsModel';
import {useRouter,Link} from '../navigation/Router';
import {DialogShell} from '../components/DialogShell';
import {MembershipEmblem} from '../components/MembershipEmblem';
import {AccountAvatar} from '../components/AccountAvatar';
import {track} from '../services/analytics';
import {viewPlans} from '../../server/viewPlans';
import '../styles/membership-recharge.css';
import '../styles/membership-layout.css';
import '../styles/view-plans.css';

type ViewPlan={id:'view-month'|'view-quarter'|'view-forever';title:string;total:number;durationDays:number|null;tier:'basic'|'premium';validity:'fixed'|'permanent'};
type Quote=ViewPlan&{currency:'CNY';quotedAt:string};
type Selected={kind:'view';quote:Quote}|{kind:'credits'};
const benefits=['VIP 剧集与漫剧畅看','会员期内观看不扣永久积分','18+ 内容仍需确认年满18周岁','不自动续费'];
const tierName=(tier:Account['tier'])=>tier==='basic'?'悦享会员':tier==='premium'?'尊享会员':'免费用户';
const formatDate=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'永久有效';
const price=(cents:number)=>`¥${(cents/100).toFixed(0)}`;

export function MembershipPage(){
 const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),points=usePoints(),overview=useMeOverview(),{route,navigate}=useRouter(),returnTo=route.params.get('returnTo');
 const festivalActive=useFestivalPhase()==='active';
 const [plans,setPlans]=useState<ViewPlan[]>([]),[planError,setPlanError]=useState(''),[catalogOffline,setCatalogOffline]=useState(false),[selected,setSelected]=useState<Selected|null>(null),[quoting,setQuoting]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[purchaseError,setPurchaseError]=useState(''),[trialBusy,setTrialBusy]=useState(false),[trialError,setTrialError]=useState('');
 const purchaseKey=useRef(crypto.randomUUID()),pending=useRef(false);
 useEffect(()=>{let cancelled=false;fetch('/api/v1/membership/view-plans',{credentials:'same-origin'}).then(async response=>{if(!response.ok)throw Error('plans_unavailable');return response.json() as Promise<ViewPlan[]>}).then(value=>{if(!cancelled){setPlans(value);setCatalogOffline(false)}}).catch(()=>{if(!cancelled){setPlans([...viewPlans]);setCatalogOffline(true);setPlanError('当前仅展示方案，购买服务暂不可用。')}});return()=>{cancelled=true}},[]);
 useEffect(()=>{track({name:'membership_view',zone:'green',experiment:'A',tier:account.tier},`membership:${route.key}`)},[route.key,account.tier]);
 useEffect(()=>{const target=route.hash==='#festival-recharge'?'festival-recharge':route.hash==='#credits'||route.hash==='#points-topup'||route.params.get('view')==='points'?'credits':null;if(target){const frame=requestAnimationFrame(()=>document.getElementById(target)?.scrollIntoView({block:'start'}));return()=>cancelAnimationFrame(frame)}},[route.hash,route.search]);
 useEffect(()=>{const offer=route.params.get('offer');if(offer==='points-220')setSelected({kind:'credits'});else if(offer&&plans.some(plan=>plan.id===offer))void quote(offer);},[route.search,plans]);
 async function quote(id:string){setQuoting(id);setPurchaseError('');try{const response=await fetch('/api/v1/membership/view-plans/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId:id})});if(!response.ok)throw Error('quote_unavailable');const value=await response.json() as Quote;purchaseKey.current=crypto.randomUUID();setSelected({kind:'view',quote:value})}catch{setPlanError('报价暂时无法获取，请稍后再试。')}finally{setQuoting(null)}}
 const purchasePath=(offerId:string)=>{const params=new URLSearchParams(route.params);params.set('view','plans');params.set('offer',offerId);return `/membership?${params}`};
 async function purchase(){if(!selected||pending.current)return;pending.current=true;setBusy(true);setPurchaseError('');try{await pointsService.purchase(selected.kind==='view'?selected.quote.id:permanentCreditsOffer.id,purchaseKey.current);await accountService.refresh();await festivalService.refresh();setSelected(null);navigate(returnTo||'/me/points')}catch(error){setPurchaseError(pointsError(error))}finally{pending.current=false;setBusy(false)}}
 async function claimTrial(){if(trialBusy)return;setTrialBusy(true);setTrialError('');try{await meService.claimTrial();await accountService.refresh()}catch(error){setTrialError(meError(error))}finally{setTrialBusy(false)}}
 const ready=account.status==='authenticated'&&points.userId===account.userId&&!points.loading&&!points.error;
 const currentPoints=ready?points.data?.summary.balance??null:null;
 const balanceText=account.status==='guest'?'登录后查看':points.loading||points.userId!==account.userId?'加载中…':points.error?'暂时无法获取':currentPoints===null?'暂时无法获取':currentPoints.toLocaleString('zh-CN');
 const lifetime=account.membership?.permanent===true||points.data?.summary.permanentMember===true;
 const currentTierName=account.tier==='free'?'免费用户':lifetime?'永久会员':!ready?'会员权益加载中…':points.data?.summary.paidViewActive?'畅看会员':`${tierName(account.tier)} · 历史积分制权益`;
 const memberBalanceText=currentPoints===null?balanceText:(points.data?.summary.memberBalance??0).toLocaleString('zh-CN');
 const trial=account.status==='authenticated'&&overview.userId===account.userId&&!overview.loading&&!overview.error?overview.data?.trial:null;
 const canConfirmPurchase=ready&&points.data?.summary.demo===true;
 const trialLabel=lifetime?'永久会员已享畅看权益':account.status==='guest'?'登录后查看体验资格':overview.loading||overview.userId!==account.userId?'体验资格加载中…':overview.error?'体验资格暂时无法获取':trial?.status==='active'?account.tier==='free'?`体验中 · 至 ${formatDate(trial.expiresAt)}`:'已领取，会员有效期增加 1 天':trial?.status==='expired'?'体验已领取':account.tier==='free'?'符合资格的账号可免费领取一次':'会员可领取一次，领取后有效期增加 1 天';
 return <main className="recharge-page membership-layout"><div className="recharge-universe" aria-hidden="true"><div className="recharge-orbit recharge-orbit-one"/><div className="recharge-orbit recharge-orbit-two"/><div className="recharge-planet"/><div className="recharge-aurora"/></div><div className="recharge-content">
  <header className="recharge-heading"><div className="recharge-heading-spark" aria-hidden="true"><Sparkles/></div><h1><span>爱爱短剧</span> 畅看会员</h1><p>会员期内畅看不扣积分 · 永久积分按需购买</p></header>
  <section className="membership-account" aria-label="账户状态"><div className="membership-account-main"><AccountAvatar tier={account.tier} hero/><div className="membership-account-copy"><div className="membership-account-title"><h2>{account.status==='guest'?'登录后查看会员权益':account.nickname||account.userId}</h2><span className="membership-status"><Crown size={15}/>{account.status==='guest'?'未登录':currentTierName}</span></div>{account.status==='authenticated'&&account.tier!=='free'&&<p className="membership-expiry"><CalendarDays size={15}/>{lifetime?'永久有效':`有效期至 ${formatDate(account.membership?.expiresAt)}`}</p>}<div className="membership-balances"><div className="membership-balance-row"><span>永久积分：<strong aria-live="polite">{balanceText}</strong></span><a href="#credits">购买永久积分 <ArrowRight size={15}/></a></div><div className="membership-balance-row"><span>会员积分：<strong aria-live="polite">{memberBalanceText}</strong></span>{!lifetime&&<a href="/me#daily-check-in">兑换畅看时长 <ArrowRight size={15}/></a>}{lifetime&&<small>历史余额保留</small>}</div></div></div></div><Link className="membership-order-button" href="/me/orders"><ReceiptText size={17}/> 我的订单</Link>{account.status==='authenticated'&&account.tier!=='free'&&<details className="membership-current-benefits"><summary>查看当前会员权益 <ArrowRight size={16}/></summary><div className="membership-benefits-content"><p>{currentTierName} · {lifetime?'无到期日':`有效期至 ${formatDate(account.membership?.expiresAt)}`}。VIP 剧集畅看；18+ 内容仍需满足访问条件。</p><p>既有积分、单集解锁和订单记录保留。</p></div></details>}</section>
  <section className="membership-trial" aria-labelledby="trial-title"><div className="membership-trial-icon"><Clock3 size={27}/><span>24h</span></div><div className="membership-trial-copy"><span className="membership-eyebrow">限时体验</span><h2 id="trial-title">24 小时免费畅看</h2><p>{trialLabel}</p>{trialError&&<p role="alert">{trialError}</p>}</div>{account.status==='guest'?<Link className="membership-trial-action" href="/account/login?returnTo=%2Fmembership">登录领取 <ArrowRight size={17}/></Link>:!lifetime&&trial?.status==='available'?<button className="membership-trial-action" disabled={trialBusy} onClick={()=>void claimTrial()}>{trialBusy?'领取中…':account.tier==='free'?'立即领取':'领取加 1 天'} <ArrowRight size={17}/></button>:<span className="membership-trial-state">{lifetime?'已享永久权益':trial?.status==='active'?'已领取':'领取机会已用完'}</span>}</section>
  <p className="membership-free-note">免费用户可直接观看免费剧集；付费单集使用永久积分解锁。签到获得的永久积分不提供会员专区权限。</p>
  {planError&&<p className="membership-plan-error" role="alert">{planError}</p>}
  <section className="recharge-tiers" id="festival-recharge" aria-label="会员方案">{plans.map((plan,index)=><article key={plan.id} className={`recharge-card recharge-${index===0?'silver':index===1?'pink':'cyan'}`}><div className="recharge-card-top"><MembershipEmblem level={index}/><h2>{plan.title}</h2><span className="plan-position">{index===0?'入门畅看':index===1?'中期畅看':'长期权益'}</span></div><div className="recharge-price-area"><div className="recharge-price"><span>¥</span><strong>{(plan.total/100).toFixed(0)}</strong><small>/{plan.validity==='permanent'?'永久':`${plan.durationDays} 天`}</small></div></div><div className="recharge-points">{plan.validity==='permanent'?'无到期日 · 观看不扣积分':'观看不扣积分 · 每日签到领会员积分'}</div>{festivalActive&&<FestivalBonus offerId={plan.id}/>}<div className="recharge-card-rule"/><ul>{benefits.map(benefit=><li key={benefit}><span className="recharge-check"><Check size={14}/></span>{benefit}</li>)}</ul><button className="recharge-cta" disabled={!!quoting||lifetime||catalogOffline} onClick={()=>void quote(plan.id)}>{catalogOffline?'购买暂不可用':lifetime?'已享永久权益':quoting===plan.id?'获取报价中…':`选择${plan.title}`}<ArrowRight size={18}/></button></article>)}</section>
  <section id="credits" className="membership-credits" aria-labelledby="credits-title"><div className="membership-credits-copy"><span className="membership-eyebrow">按需补充</span><h2 id="credits-title"><Coins size={23}/> 永久积分</h2><p>积分永不过期，可重复购买。</p><small>免费用户付费单集 5 积分；永久积分不能换取会员专区权限。</small></div><div className="membership-credit-options" aria-label="永久积分套餐"><span className="membership-credit-quantity"><strong>{permanentCreditsOffer.points} 积分</strong></span><span className="membership-credit-price">¥{permanentCreditsOffer.price}</span><button className="membership-credit-cta" onClick={()=>{purchaseKey.current=crypto.randomUUID();setSelected({kind:'credits'})}}>购买永久积分 <ArrowRight size={17}/></button></div></section>
  <nav className="membership-footer-links" aria-label="会员服务"><Link href="/me/orders">我的订单 <ArrowRight size={15}/></Link><Link href="/membership-guide">会员与积分说明 <ArrowRight size={15}/></Link></nav><p className="membership-payment-note"><ShieldCheck size={15}/> 支付前请核对商品、金额及账户；18+ 专区需确认年满18周岁。已解锁剧集永久保留。</p>
 </div>{selected&&<DialogShell title={selected.kind==='view'?selected.quote.title:'购买永久积分'} onClose={()=>setSelected(null)} hideFooterClose><div className={`recharge-purchase ${selected.kind==='credits'?'recharge-cyan':'recharge-pink'}`}><div className="recharge-purchase-symbol" aria-hidden="true">{selected.kind==='view'?<Crown/>:<Coins/>}</div><div className="recharge-price"><span>¥</span><strong>{selected.kind==='view'?(selected.quote.total/100).toFixed(0):permanentCreditsOffer.price}</strong></div><p className="purchase-benefit-label">{selected.kind==='view'?selected.quote.validity==='permanent'?'永久有效 · 无到期日':`${selected.quote.durationDays} 天畅看权益`:`${permanentCreditsOffer.points} 永久积分`}</p>{selected.kind==='view'&&<p>服务端报价 {price(selected.quote.total)} · 购买前确认</p>}{festivalActive&&selected.kind==='view'&&extraViewingDaysFor(selected.quote.id)>0&&<div className="purchase-festival-bonus"><span>双节活动加赠</span><strong>{extraViewingDaysFor(selected.quote.id)} 天畅看</strong><small>活动期内支付成功后计入会员有效期</small></div>}{account.status==='guest'?<Link className="recharge-cta" href={`/account/login?returnTo=${encodeURIComponent(purchasePath(selected.kind==='view'?selected.quote.id:permanentCreditsOffer.id))}`}>登录后继续 <ArrowRight size={18}/></Link>:<><p>{canConfirmPurchase?'本地演示订单，不会发生真实扣款。':'支付服务暂不可用，请稍后再试。'}</p>{purchaseError&&<p role="alert">{purchaseError}</p>}<button className="recharge-cta" disabled={busy||!canConfirmPurchase} onClick={()=>void purchase()}>{busy?'处理中…':canConfirmPurchase?'确认演示购买':'支付暂不可用'}</button></>}</div></DialogShell>}</main>;
}
function FestivalBonus({offerId}:{offerId:string}){const days=extraViewingDaysFor(offerId);return days>0?<span className="membership-festival-bonus">双节活动额外赠 <b>{days}</b> 天畅看</span>:null}
