import{useEffect,useSyncExternalStore}from'react';
import{ArrowUpRight,BadgeCheck,CalendarDays,Check,Crown,Gauge,Headphones,ReceiptText,ShieldCheck,Sparkles}from'lucide-react';
import{accountService,plans,type Account}from'../services/membership';
import{useRouter,Link}from'../navigation/Router';
import{PageHeading}from'../components/content/PageParts';
import{AccountAvatar}from'../components/AccountAvatar';
import{track}from'../services/analytics';

const tierName=(tier:Account['tier'])=>tier==='basic'?'基础会员':tier==='premium'?'高级会员':'免费用户';
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'以权益记录为准';

export function MembershipPage(){
 const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),{route}=useRouter(),returnTo=route.params.get('returnTo');
 useEffect(()=>{track({name:'membership_view',zone:'green',experiment:'A',tier:account.tier},`membership:${route.key}`);},[route.key]);
 if(account.status==='authenticated'&&account.tier!=='free')return <MemberCenter account={account} returnTo={returnTo}/>;
 return <main className="container page membership-page"><PageHeading eyebrow="AIAI · MEMBERSHIP" title="一份会员，更多好故事" description="按需选择会员期限，购买前可再次确认方案与价格。"/><div className="membership-current surface-panel"><Crown/><div><strong>当前：{tierName(account.tier)}</strong><p>{account.status==='guest'?'登录后可查看会员有效期和订单。':'开通会员后可在这里查看等级、有效期和权益。'}</p></div><Link className="text-button" href="/me/orders">我的订单 <ArrowUpRight size={16}/></Link></div><div className="plans-grid">{plans.map(plan=><section key={plan.id} className={`plan-card surface-panel ${plan.id==='premium-month'?'featured-plan':''}`}>{plan.id==='premium-month'&&<span className="plan-flag">热门选择</span>}<span className="eyebrow">{tierName(plan.tier)}</span><h2>{plan.title}</h2><div className="plan-price"><span>¥</span>{plan.prices.A}<small> / {plan.period}</small></div><p className="plan-total">有效期 {plan.duration} · 总价 ¥{plan.prices.A}</p><ul>{plan.benefits.map(item=><li key={item}><Check size={16}/>{item}</li>)}</ul><Link className={plan.id==='premium-month'?'primary-button':'secondary-button'} href={`/checkout?plan=${plan.id}${returnTo?`&returnTo=${encodeURIComponent(returnTo)}`:''}`}>选择方案</Link></section>)}</div><section className="surface-panel membership-notes"><h2>购买说明</h2><p>会员仅包含页面明确列出的内容权益，不等同于专区访问资格。实际可观看内容还取决于作品授权和上线状态。</p><p>当前方案均为一次性购买，不自动续费。退款与权益变更以会员说明和订单状态为准。</p></section></main>;
}

function MemberCenter({account,returnTo}:{account:Account;returnTo:string|null}){
 const membership=account.membership,level=membership?.level,growth=membership?.growth??0,next=membership?.nextLevelGrowth??0,progress=next?Math.min(100,Math.round(growth/next*100)):0;
 const benefits=[
  {icon:<Crown/>,title:'高级会员内容',body:'可观看已上线并标注为高级会员的内容。'},
  {icon:<BadgeCheck/>,title:'包含基础权益',body:'高级会员同时包含已上线的基础会员内容。'},
  {icon:<Sparkles/>,title:'专属身份标识',body:'页头与个人中心展示会员头像光环和皇冠标识。'},
  {icon:<ShieldCheck/>,title:'权益状态可查',body:'可从订单页面查看购买记录和权益处理状态。'},
 ];
 return <main className="container page member-center"><section className="member-center-hero"><div className="member-identity"><AccountAvatar tier={account.tier} hero/><div><span className="member-tier"><Crown/> {tierName(account.tier)}</span><h1>{account.nickname||account.userId}</h1><p><CalendarDays/> 有效期至 {date(membership?.expiresAt)}</p></div></div><div className="member-hero-actions"><Link className="secondary-button" href="/me/orders"><ReceiptText/> 我的订单</Link><a className="primary-button" href="#renew">续费会员</a></div></section><section className="member-level surface-panel"><div className="member-level-mark"><Gauge/><span>会员等级</span><strong>{level?`V${level}`:'待同步'}</strong></div><div className="member-growth"><div><strong>{level?`V${level} · 入戏玩家`:'等级信息同步中'}</strong>{next>0&&<span>{growth} / {next} 成长值</span>}</div><div className="member-growth-track" role="progressbar" aria-label="会员成长进度" aria-valuemin={0} aria-valuemax={next||100} aria-valuenow={growth}><span style={{width:`${progress}%`}}/></div><p>{level?`再获得 ${Math.max(0,next-growth)} 成长值可提升等级。成长规则以正式会员规则为准。`:'会员等级以账号权益服务返回结果为准。'}</p></div></section><section className="member-section"><div className="member-section-heading"><div><span className="eyebrow">MY BENEFITS</span><h2>我的会员权益</h2></div><Link className="text-button" href="/membership-guide">查看会员说明 <ArrowUpRight/></Link></div><div className="member-benefits">{benefits.map(item=><article className="surface-panel" key={item.title}>{item.icon}<h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section><section className="member-section member-services"><div className="member-section-heading"><div><span className="eyebrow">MEMBER SERVICE</span><h2>会员服务</h2></div></div><div className="member-service-links"><Link className="surface-panel" href="/me/orders"><ReceiptText/><span><strong>订单与权益</strong><small>查看订单状态和权益记录</small></span><ArrowUpRight/></Link><Link className="surface-panel" href="/support/membership"><Headphones/><span><strong>会员帮助</strong><small>查看会员使用问题</small></span><ArrowUpRight/></Link></div></section><section id="renew" className="member-section"><div className="member-section-heading"><div><span className="eyebrow">RENEW MEMBERSHIP</span><h2>续费会员</h2><p>续费前请再次核对期限和价格。</p></div></div><div className="member-renew-grid">{plans.filter(plan=>plan.tier===account.tier).map(plan=><article className="surface-panel" key={plan.id}><div><span>{plan.duration}</span><h3>{plan.title}</h3><p>一次性购买，不自动续费</p></div><strong>¥{plan.prices.A}</strong><Link className="secondary-button" href={`/checkout?plan=${plan.id}${returnTo?`&returnTo=${encodeURIComponent(returnTo)}`:''}`}>查看方案</Link></article>)}</div></section></main>;
}
