import{useEffect,useState,useSyncExternalStore}from'react';import{Check,Crown,ArrowUpRight}from'lucide-react';
import{accountService,plans,type PlanId}from'../services/membership';import{hasBaseBenefits}from'../services/rules';import{useRouter,Link}from'../navigation/Router';import{DialogShell}from'../components/DialogShell';import{PageHeading}from'../components/content/PageParts';import{useAccess}from'../services/hooks';import{track}from'../services/analytics';
export function MembershipPage(){const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),access=useAccess(),{route}=useRouter();const[choice,setChoice]=useState<PlanId|null>(null),[quote,setQuote]=useState<Awaited<ReturnType<typeof accountService.quote>>>(null),[message,setMessage]=useState('');const adult=route.params.get('context')==='adult'&&access.granted;
 useEffect(()=>{track({name:'membership_view',zone:adult?'adult':'green',experiment:account.experiment,tier:account.tier},`membership:${route.key}`);},[route.key]);
 useEffect(()=>{let active=true;setQuote(null);if(choice)void accountService.quote(choice).then(value=>{if(active)setQuote(value);});return()=>{active=false;};},[choice,account.experiment]);
 const select=(id:PlanId)=>{setMessage('');setChoice(id);if(account.tier==='basic'&&id!=='basic-month')track({name:'upgrade_start',zone:adult?'adult':'green',experiment:account.experiment,tier:account.tier});};
 return <main className="container page membership-page"><PageHeading eyebrow="AIAI · MEMBERSHIP" title="一份会员，更多好故事" description="高级会员包含基础会员全部权益。按需选择，不重复购买。"/><div className="membership-current surface-panel"><Crown/><div><strong>当前：{account.tier==='free'?'免费用户':account.tier==='basic'?'基础会员':'高级会员'}</strong><p>{account.status==='guest'?'账号与购买服务即将开放。':'账号与购买服务即将开放。'}{hasBaseBenefits(account.tier)?'基础权益已包含。':''}</p></div><Link className="text-button" href="/me/orders">我的订单 <ArrowUpRight size={16}/></Link></div>
 <div className="plans-grid">{plans.map(plan=><section key={plan.id} className={`plan-card surface-panel ${plan.id==='premium-month'?'featured-plan':''}`}>{plan.id==='premium-month'&&<span className="plan-flag">包含基础全部权益</span>}<span className="eyebrow">{plan.tier==='basic'?'基础权益':'高级权益'}</span><h2>{plan.title}</h2><div className="plan-price"><span>¥</span>{plan.prices[account.experiment]}<small> / {plan.period}</small></div><p className="plan-total">每{plan.period}总价 ¥{plan.prices[account.experiment]}</p><ul><li><Check size={16}/>精选内容免广告</li><li><Check size={16}/>高清、追剧与历史</li>{plan.tier==='premium'&&<><li><Check size={16}/>包含基础会员全部权益</li><li><Check size={16}/>{adult?'按内容规则覆盖大部分专区短剧与漫剧':'专区权益需满足访问条件'}</li></>}</ul><button className={plan.id==='premium-month'?'primary-button':'secondary-button'} onClick={()=>select(plan.id)}>{account.tier==='basic'&&plan.tier==='premium'?'查看升级高级会员':account.tier==='premium'&&plan.tier==='basic'?'基础权益已包含':'查看方案'}</button></section>)}</div>
 <div className="surface-panel membership-notes"><h2>权益清楚，选择从容</h2><p>免费用户可以浏览精选内容，正式免费播放可包含广告。专区资格与会员等级独立，即使高级会员也需要完成访问确认。</p><p>升级差额、剩余有效期、续费规则和最终结算价格以订单服务返回为准；当前不计算未经确认的差额，也不提供支付。季卡采用高级权益，不提供永久会员。</p><p>隐藏历史、清除本地记录和通知脱敏对所有用户开放。</p></div>
 {choice&&<DialogShell title={account.tier==='basic'&&choice!=='basic-month'?'升级方案确认':'方案确认'} onClose={()=>setChoice(null)}>{quote?<><p>{quote.plan.title}</p><div className="confirmation-price">¥{quote.total}<small> / {quote.plan.period}</small></div><p>升级实际差额和有效期尚未由结算服务确认。</p><p className="subtle-notice">购买服务即将开放。</p><button className="primary-button" onClick={()=>void accountService.checkout().then(r=>setMessage(r.message))}>查看开通状态</button>{message&&<p role="status">{message}</p>}</>:<p role="status">正在获取方案…</p>}</DialogShell>}</main>;
}
