import {useEffect,useState,useSyncExternalStore} from 'react';
import {Zap} from 'lucide-react';
import {Link,useRouter} from '../navigation/Router';
import {accountService} from '../services/membership';
import {pointsService,usePoints} from '../services/points';
import {pointsTierName} from '../services/pointsModel';
import {CheckInDialog} from '../components/CheckInDialog';
import {EmptyState} from '../components/content/PageParts';
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
export function PointsPage(){
 const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),points=usePoints(),{navigate}=useRouter(),[tab,setTab]=useState((['transactions','member'].includes(new URLSearchParams(location.search).get('tab')??'')?new URLSearchParams(location.search).get('tab')!:'unlocks')),[checkIn,setCheckIn]=useState(false),data=points.data;
 useEffect(()=>{if(account.status==='guest'&&!location.pathname.startsWith('/account/'))void accountService.refresh().then(()=>{if(accountService.getSnapshot().status==='guest')navigate('/account/login?returnTo=%2Fme%2Fpoints',{replace:true});});},[account.status]);
 return <main className="container page points-page"><h1>积分与解锁</h1><p className="muted">积分长期有效，已解锁剧集永久保留。</p>{account.status==='guest'?<p>登录后查看你的积分账户。</p>:points.error?<div role="alert"><p>{points.error}</p><button className="secondary-button" onClick={()=>void pointsService.refresh()}>重新加载积分</button></div>:!data?<p role="status">正在加载积分…</p>:<><section className="surface-panel points-summary"><div><span><Zap size={18}/> 永久积分</span><strong>{data.summary.balance}</strong><span>会员积分 <strong>{(data.summary.memberBalance??0)}</strong></span></div><div><h2>{pointsTierName[data.summary.tier]}</h2><p>普通签到得永久积分；有效付费畅看会员签到得会员积分，会员积分仅用于兑换时长。</p>{data.summary.monthlyAllowance>0&&<p>历史会员权益：每月赠送 {data.summary.monthlyAllowance} 积分，保留至到期。</p>}<p>两种积分分别记账，不能互换；永久积分不提供会员专区权限。</p></div><div className="points-summary-actions"><button className="secondary-button" disabled={data.summary.checkedInToday} aria-label={data.summary.checkedInToday?'今日已签到':'去签到'} onClick={()=>setCheckIn(true)}>{data.summary.checkedInToday?'今日已签到':'去签到'}</button><Link className="primary-button" href={(data.summary.memberBalance??0)>=20?'/me#daily-check-in':'/membership?view=points#credits'}>{(data.summary.memberBalance??0)>=20?'兑换畅看时长':'购买永久积分'}</Link></div></section>
 <div className="segmented points-tabs" aria-label="积分记录分类">{[['unlocks','已解锁'],['transactions','永久积分明细'],['member','会员积分明细']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='member'?((data.memberTransactions??[]).length?<div className="points-records">{(data.memberTransactions??[]).map(item=><article className="surface-panel points-transaction" key={item.id}><div><h2>{item.type==='member_check_in'?'会员积分 · 签到':'会员积分 · 兑换'}</h2><p>{item.title}</p><small>{date(item.createdAt)}</small>{item.redemptionTier&&<p>档位：{item.redemptionTier} · 兑换前到期：{item.expiresBefore?date(item.expiresBefore):'无'} · 兑换后到期：{item.expiresAfter?date(item.expiresAfter):'无'}</p>}</div><div><strong className={item.amount>=0?'points-income':''}>{item.amount>=0?'+':''}{item.amount}</strong><p>会员积分余额：{item.balanceAfter}</p></div></article>)}</div>:<EmptyState title="暂无会员积分明细" description="会员签到及兑换记录会显示在这里。"/>):tab==='unlocks'?(data.unlocks.length?<div className="points-records">{data.unlocks.map(item=><article className="surface-panel points-record" key={item.id}>{item.coverUrl&&<img src={item.coverUrl} alt=""/>}<div><h2>{item.contentTitle}</h2><p>{item.episodeTitle} · 消耗{item.pointsSpent}永久积分</p><small>{date(item.unlockedAt)}</small></div><Link className="secondary-button" href={item.href}>继续观看</Link></article>)}</div>:<EmptyState title="还没有解锁记录" description="使用积分解锁的剧集会显示在这里。"><Link className="primary-button" href="/shorts">去发现短剧</Link></EmptyState>):(data.transactions.length?<div className="points-records">{data.transactions.map(item=><article className="surface-panel points-transaction" key={item.id}><div><h2>永久积分 · {item.title}</h2><small>{date(item.createdAt)}</small>{item.activityId&&<details><summary>活动关联记录</summary><p>活动ID：{item.activityId}</p><p>奖励ID：{item.rewardId}</p>{item.invitationId&&<p>邀请ID：{item.invitationId}</p>}{item.orderId&&<p>订单ID：{item.orderId}</p>}{item.reversalStatus==='insufficient_balance'&&<p>回收待处理：余额不足，尚有{item.unrecoveredAmount}积分未回收</p>}</details>}</div><div><strong className={item.amount>=0?'points-income':''}>{item.amount>=0?'+':''}{item.amount}</strong><p>永久积分余额：{item.balanceAfter}</p></div></article>)}</div>:<EmptyState title="暂无积分明细" description="积分的增加和使用记录会显示在这里。"/>)}</>}{checkIn&&<CheckInDialog onClose={()=>setCheckIn(false)}/>}</main>;
}
