import{useState,useSyncExternalStore}from'react';
import{PageHeading,EmptyState}from'../components/content/PageParts';import{Link}from'../navigation/Router';import{accountService}from'../services/membership';import{AccountNav}from'../components/AccountNav';
import{AccountAvatar}from'../components/AccountAvatar';import{avatarStore}from'../state/avatar';
function Guard({children,returnTo}:{children:React.ReactNode;returnTo:string}){const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot);return account.status==='guest'?<main className="container page"><AccountNav/><EmptyState title="请先登录" description="登录后同步并管理你的个人内容。"><Link className="primary-button" href={`/account/login?returnTo=${encodeURIComponent(returnTo)}`}>登录 / 注册</Link></EmptyState></main>:<>{children}</>}
export function FavoritesPage(){return <Guard returnTo="/me/favorites"><main className="container page"><AccountNav/><PageHeading title="我的追剧" description="收藏喜欢的作品，方便继续观看。"/><EmptyState title="还没有追剧" description="去发现一部喜欢的故事吧。"><Link className="primary-button" href="/shorts">去发现短剧</Link></EmptyState></main></Guard>}
export function HistoryPage(){return <Guard returnTo="/me/history"><main className="container page"><AccountNav/><PageHeading title="观看历史" description="从上次停下的位置继续。"/><EmptyState title="还没有观看记录" description="去发现喜欢的故事吧。"><Link className="primary-button" href="/shorts">去发现短剧</Link></EmptyState></main></Guard>}
export function ProfilePage(){const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),[nickname,setNickname]=useState(account.nickname||''),[bio,setBio]=useState(''),[message,setMessage]=useState(''),[avatarMessage,setAvatarMessage]=useState('');return <Guard returnTo="/me/profile"><main className="container page"><AccountNav/><PageHeading title="个人资料" description="设置其他用户看到的名称、头像和个人简介。"/><div className="account-detail-column"><section className="surface-panel avatar-editor"><AccountAvatar tier={account.tier} hero/><div><h2>头像</h2><p>未上传图片时，默认显示用户名首字母。头像保存在当前设备。</p><div className="inline-actions"><label className="secondary-button avatar-upload-button">更换头像<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async event=>{const file=event.target.files?.[0];if(!file||!account.userId)return;setAvatarMessage('');try{await avatarStore.fromFile(account.userId,file);setAvatarMessage('头像已更新。');}catch(error){setAvatarMessage(error instanceof Error?error.message:'头像更新失败。');}event.currentTarget.value='';}}/></label><button type="button" className="text-button" onClick={()=>{if(account.userId)avatarStore.remove(account.userId);setAvatarMessage('已恢复默认头像。');}}>恢复默认</button></div>{avatarMessage&&<p className="avatar-editor-status" role="status">{avatarMessage}</p>}</div></section><form className="surface-panel profile-form" onSubmit={event=>{event.preventDefault();setMessage('资料服务暂时不可用，请稍后再试。');}}><label>登录账号<input value={account.userId||''} disabled/></label><label>昵称<input value={nickname} minLength={2} maxLength={24} onChange={event=>setNickname(event.target.value)} required/></label><label>个人简介<textarea value={bio} maxLength={120} onChange={event=>setBio(event.target.value)}/><small>{bio.length}/120</small></label><button className="primary-button">保存资料</button>{message&&<p className="field-error" role="alert">{message}</p>}</form><section className="surface-panel danger-panel"><h2>账号安全</h2><p>通过绑定邮箱找回密码，定期更新密码有助于保护账号。</p><Link className="secondary-button" href="/account/forgot-password?returnTo=%2Fme%2Fprofile">修改密码</Link></section></div></main></Guard>}
export function MyCommentsPage(){return <Guard returnTo="/me/comments"><main className="container page"><AccountNav/><PageHeading title="我的评论" description="查看你发表和参与的剧情讨论。"/><EmptyState title="还没有评论" description="看剧时留下你的想法吧。"><Link className="primary-button" href="/shorts">去看短剧</Link></EmptyState></main></Guard>}
export function MessagesPage(){const[kind,setKind]=useState('all');return <Guard returnTo="/me/messages"><main className="container page"><AccountNav/><PageHeading title="消息中心" description="查看回复、追剧更新和系统消息。"/><div className="segmented message-filters">{[['all','全部'],['reply','回复'],['update','追剧更新'],['system','系统']].map(([id,label])=><button key={id} aria-pressed={kind===id} onClick={()=>setKind(id)}>{label}</button>)}</div><EmptyState title="暂无消息"/></main></Guard>}
