import{useState,useSyncExternalStore}from'react';
import{CircleHelp,FileQuestion,ArrowUpRight}from'lucide-react';
import{PageHeading,EmptyState}from'../components/content/PageParts';import{Link,useRouter}from'../navigation/Router';import{accountService}from'../services/membership';import{createHttpBackend}from'../services/backend';import{AccountNav}from'../components/AccountNav';
const api=createHttpBackend(()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'');
const faqs=[
 ['account','账号与登录','如何注册账号？','点击页面右上角“登录 / 注册”，切换到注册，设置账号和密码即可。邮箱可以选填；绑定邮箱后可用于找回密码。'],
 ['playback','播放问题','视频无法播放怎么办？','请检查网络并重新加载页面。如果某一集仍无法播放，可能是该集暂未上线或当前地区暂不可用。'],
 ['membership','会员与权益','会员可以观看哪些内容？','作品页会标明所需会员等级。高级会员包含基础会员内容，专区访问资格需单独满足相关条件。'],
 ['orders','订单与退款','在哪里查看订单状态？','登录后进入“我的－我的订单”，可以查看支付状态和会员权益是否生效。退款范围和处理时间以会员说明为准。'],
 ['privacy','记录与隐私','如何管理观看记录？','进入“我的－观看历史”可以继续观看或删除记录；隐私设置中还可以管理当前设备保存的关注与私密记录。'],
] as const;
export function HelpPage({topic}:{topic?:string}){const faq=faqs.find(item=>item[0]===topic);if(faq)return <main className="container page narrow-page"><PageHeading title={faq[1]} description="常见问题与使用指引。"/><article className="surface-panel help-article"><CircleHelp/><h2>{faq[2]}</h2><p>{faq[3]}</p><Link className="secondary-button" href="/support">返回帮助中心</Link></article></main>;return <main className="container page"><PageHeading title="帮助中心" description="查找账号、播放、会员、订单和隐私问题。"/><div className="help-grid">{faqs.map(item=><Link className="surface-panel" href={`/support/${item[0]}`} key={item[0]}><FileQuestion/><h2>{item[1]}</h2><p>{item[2]}</p><ArrowUpRight/></Link>)}</div><div className="page-actions"><Link className="primary-button" href={`/support/feedback?source=${encodeURIComponent(location.pathname+location.search)}`}>提交反馈</Link><Link className="secondary-button" href="/support/tickets">我的反馈</Link></div></main>}
export function FeedbackPage(){const{route,navigate}=useRouter(),account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),[category,setCategory]=useState('播放问题'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),source=route.params.get('source')||'',context=Object.fromEntries([['source',source],['order',route.params.get('order')||''],['drama',route.params.get('drama')||'']].filter(([,value])=>value));if(account.status==='guest')return <main className="container page"><EmptyState title="登录后提交反馈" description="登录后可以提交问题并查看处理进度。"><Link className="primary-button" href={`/account/login?returnTo=${encodeURIComponent(location.pathname+location.search)}`}>登录 / 注册</Link></EmptyState></main>;const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const ticket=await api.createTicket({category,subject:subject.trim(),description:description.trim(),context});navigate(`/support/tickets/${ticket.id}`);}catch{setMessage('反馈服务暂时不可用，请稍后再试。');}finally{setBusy(false);}};return <main className="container page narrow-page"><PageHeading title="意见反馈" description="请详细描述问题，我们会根据关联页面帮助定位。"/><form className="surface-panel form-stack" onSubmit={submit}><label>问题类型<select value={category} onChange={event=>setCategory(event.target.value)}><option>账号问题</option><option>播放问题</option><option>会员与订单</option><option>评论举报</option><option>隐私与记录</option><option>版权反馈</option></select></label><label>主题<input value={subject} minLength={3} maxLength={80} onChange={event=>setSubject(event.target.value)} required/></label><label>问题描述<textarea value={description} minLength={10} maxLength={1000} onChange={event=>setDescription(event.target.value)} required/></label>{source&&<div className="context-preview"><strong>问题来源</strong><p>{source}</p></div>}<button className="primary-button" disabled={busy}>{busy?'正在提交…':'提交反馈'}</button>{message&&<p className="field-error" role="alert">{message}</p>}</form></main>}
export function TicketsPage({id}:{id?:string}){const account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot);if(account.status==='guest')return <main className="container page"><AccountNav/><EmptyState title="登录后查看反馈" description="反馈记录只对提交者本人可见。"><Link className="primary-button" href="/account/login?returnTo=%2Fsupport%2Ftickets">登录</Link></EmptyState></main>;return <main className="container page"><AccountNav/><PageHeading title={id?'反馈详情':'我的反馈'} description="查看问题处理进度。"/><EmptyState title={id?'暂时无法加载反馈':'暂无反馈'} description={id?'反馈服务当前不可用，请稍后再试。':'遇到问题时，可以向我们提交反馈。'}>{!id&&<Link className="primary-button" href={`/support/feedback?source=${encodeURIComponent('/support/tickets')}`}>提交反馈</Link>}</EmptyState></main>}
export function PolicyPage({kind}:{kind:'terms'|'privacy'|'membership'|'copyright'|'about'}){const copy={terms:{title:'服务协议',intro:'本页面说明账号、内容浏览、会员购买和社区互动的基本使用规则。',sections:[['账号使用','请妥善保管账号和密码，不得冒用他人身份或利用服务从事违法活动。'],['内容与互动','请尊重版权和其他用户，评论不得包含违法、侵权、骚扰或泄露隐私的内容。'],['服务变更','作品上线状态和可用范围可能因授权、地区或运营安排发生变化。']]},privacy:{title:'隐私政策',intro:'我们仅在提供账号、播放记录、订单与互动功能所需范围内处理信息。',sections:[['账号信息','注册时处理账号、加密后的密码凭据，以及你自愿填写的电子邮箱。'],['使用记录','登录后可保存收藏、观看进度、评论、订单和反馈记录。'],['你的选择','你可以管理设备记录，并在正式服务接入后申请访问、更正或删除账号数据。']]},membership:{title:'会员说明',intro:'会员权益按所选方案和有效期提供，作品可用性仍受授权与上线状态影响。',sections:[['方案与价格','购买前页面会展示方案名称、期限和应付总额；当前方案不自动续费。'],['权益生效','支付成功并经订单服务确认后，会员权益才会生效。'],['退款处理','退款条件、处理进度和权益回收以订单页面及正式运营规则为准。']]},copyright:{title:'版权与侵权反馈',intro:'如认为站内内容侵犯合法权益，请通过反馈页面提交作品链接、权属说明和联系方式。',sections:[['所需材料','请提供权利人身份证明、权属证明、涉嫌侵权内容位置和具体请求。'],['处理方式','我们会在核实材料后采取必要措施，并通过反馈记录更新处理状态。']]},about:{title:'关于爱爱短剧',intro:'爱爱短剧专注于发现和观看短篇故事。',sections:[['我们的内容','通过分类、片单和搜索帮助用户找到感兴趣的短剧与漫剧。'],['联系我们','运营主体、正式客服联系方式和相关资质将在确认后公布。']]}}[kind];return <main className="container page narrow-page"><PageHeading title={copy.title} description={copy.intro}/><article className="surface-panel policy-copy">{copy.sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}{kind==='copyright'&&<Link className="primary-button" href={`/support/feedback?source=${encodeURIComponent('/copyright')}`}>提交版权反馈</Link>}</article></main>}
