import{useEffect,useMemo,useState,useSyncExternalStore}from'react';
import{Heart,MessageSquareReply,Flag,Trash2}from'lucide-react';
import{accountService}from'../services/membership';
import{createHttpBackend,type CommentDTO}from'../services/backend';
import{useRouter}from'../navigation/Router';
import{DialogShell}from'./DialogShell';
const api=createHttpBackend(()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content??'');
const time=(value:string)=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
export function Comments({dramaId,episodeId,episodeNumber}:{dramaId:string;episodeId:string;episodeNumber:number}){const{navigate}=useRouter(),account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),draftKey=`aiai:comment-draft:${dramaId}:${episodeId}`,[draft,setDraft]=useState(()=>sessionStorage.getItem(draftKey)||''),[spoiler,setSpoiler]=useState(false),[sort,setSort]=useState<'latest'|'hot'>('latest'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[items,setItems]=useState<CommentDTO[]>([]),[replyTo,setReplyTo]=useState<CommentDTO|null>(null),[report,setReport]=useState<CommentDTO|null>(null);useEffect(()=>{const controller=new AbortController();api.comments(dramaId,episodeId,undefined,controller.signal).then(result=>setItems(result.items)).catch(()=>{});return()=>controller.abort();},[dramaId,episodeId]);useEffect(()=>{if(draft)sessionStorage.setItem(draftKey,draft);else sessionStorage.removeItem(draftKey);},[draft,draftKey]);const list=useMemo(()=>items.filter(item=>!item.parentId).sort((a,b)=>sort==='hot'?b.likeCount-a.likeCount:b.createdAt.localeCompare(a.createdAt)),[items,sort]);
 const publish=async(event:React.FormEvent)=>{event.preventDefault();setError('');if(account.status==='guest'){sessionStorage.setItem(draftKey,draft);navigate(`/account/login?returnTo=${encodeURIComponent(`${location.pathname}${location.search}#comments`)}`);return;}if(busy)return;setBusy(true);try{const created=await api.createComment({contentId:dramaId,episodeId,parentId:replyTo?.id,content:draft.trim(),spoiler},crypto.randomUUID());setItems(current=>[created,...current]);setDraft('');setSpoiler(false);setReplyTo(null);}catch{setError('暂时无法发表评论，请稍后再试。');}finally{setBusy(false);}};
 return <section id="comments" className="comments-section" aria-labelledby="comments-heading"><header><div><span className="eyebrow">第 {episodeNumber} 集</span><h2 id="comments-heading">评论与讨论</h2><p>友善交流，一起聊聊剧情。</p></div><div className="segmented" aria-label="评论排序"><button aria-pressed={sort==='hot'} onClick={()=>setSort('hot')}>热门</button><button aria-pressed={sort==='latest'} onClick={()=>setSort('latest')}>最新</button></div></header><form className="comment-composer surface-panel" onSubmit={publish}><label htmlFor="comment-body">{replyTo?`回复 ${replyTo.author.nickname}`:'发表评论'}</label><textarea id="comment-body" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="尊重彼此，聊聊这一集…" minLength={2} maxLength={500} required/><div><label className="checkbox-label"><input type="checkbox" checked={spoiler} onChange={event=>setSpoiler(event.target.checked)}/>包含剧透</label><span>{draft.length}/500</span>{replyTo&&<button type="button" className="text-button" onClick={()=>setReplyTo(null)}>取消回复</button>}<button className="primary-button" disabled={busy}>{busy?'正在提交…':'发表评论'}</button></div>{account.status==='guest'&&<p className="comment-hint">提交时需要先登录，草稿会为你保留。</p>}{error&&<p className="field-error" role="alert">{error}</p>}</form><div className="comment-list">{list.map(comment=><CommentItem key={comment.id} item={comment} currentUser={account.userId} onReply={setReplyTo} onReport={setReport} onChange={setItems}/>)}</div>{!list.length&&<p className="comments-empty">还没有评论，来聊聊这一集吧。</p>}{report&&<ReportDialog comment={report} onClose={()=>setReport(null)}/>}</section>;
}
function CommentItem({item,currentUser,onReply,onReport,onChange}:{item:CommentDTO;currentUser:string|null;onReply:(item:CommentDTO)=>void;onReport:(item:CommentDTO)=>void;onChange:React.Dispatch<React.SetStateAction<CommentDTO[]>>}){const[revealed,setRevealed]=useState(!item.spoiler),[error,setError]=useState('');const like=async()=>{if(!currentUser){onReply(item);return;}try{const result=await api.toggleCommentLike(item.id,!item.liked);onChange(list=>list.map(value=>value.id===item.id?{...value,...result}:value));}catch{setError('操作失败，请稍后再试。');}};const remove=async()=>{try{await api.deleteComment(item.id);onChange(list=>list.filter(value=>value.id!==item.id&&value.parentId!==item.id));}catch{setError('暂时无法删除，请稍后再试。');}};return <article className="comment-item"><div className="comment-avatar" aria-hidden="true">{item.author.nickname.slice(0,1)}</div><div className="comment-body"><header><strong>{item.author.nickname}</strong><time dateTime={item.createdAt}>{time(item.createdAt)}</time></header>{item.spoiler&&!revealed?<button className="spoiler-cover" onClick={()=>setRevealed(true)}>本评论包含剧透，点击展开</button>:<p>{item.content}</p>}<div className="comment-actions"><button aria-pressed={item.liked} onClick={()=>void like()}><Heart size={15} fill={item.liked?'currentColor':'none'}/>{item.likeCount}</button>{currentUser&&<button onClick={()=>onReply(item)}><MessageSquareReply size={15}/>回复</button>}{currentUser===item.author.id?<button onClick={()=>void remove()}><Trash2 size={15}/>删除</button>:currentUser&&<button onClick={()=>onReport(item)}><Flag size={15}/>举报</button>}</div>{error&&<p className="field-error" role="alert">{error}</p>}</div></article>}
function ReportDialog({comment,onClose}:{comment:CommentDTO;onClose:()=>void}){const[reason,setReason]=useState('垃圾广告'),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const submit=async()=>{setBusy(true);try{await api.reportComment(comment.id,reason);setDone(true);}catch{setError('暂时无法提交举报，请稍后再试。');}finally{setBusy(false);}};return <DialogShell title="举报评论" onClose={onClose}>{done?<p role="status">举报已提交，我们会尽快处理。</p>:<><p>请选择举报原因。举报不会自动删除评论。</p><label>举报原因<select value={reason} onChange={event=>setReason(event.target.value)}><option>垃圾广告</option><option>人身攻击</option><option>违法违规</option><option>泄露隐私</option></select></label>{error&&<p className="field-error" role="alert">{error}</p>}<button className="primary-button" disabled={busy} onClick={()=>void submit()}>{busy?'正在提交…':'提交举报'}</button></>}</DialogShell>}
