import{useId,useLayoutEffect,useRef,type ReactNode}from'react';
import{X}from'lucide-react';
import{timing}from'../config';
import{useReducedMotion}from'../hooks/useReducedMotion';
export function DialogShell({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),close=useRef(()=>{}),done=useRef(onClose),id=useId();const reduced=useReducedMotion();done.current=onClose;
 useLayoutEffect(()=>{const dialog=ref.current!,trigger=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;let disposed=false,closing=false;const animations:Animation[]=[];document.body.style.overflow='hidden';dialog.showModal();close.current=()=>{if(disposed||closing)return;closing=true;const finish=()=>{if(!disposed){dialog.close();done.current();}};if(reduced){finish();return;}const animation=dialog.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.97)'}],{duration:timing.modalClose,fill:'forwards',easing:'ease-out'});animations.push(animation);void animation.finished.then(finish,()=>{});};return()=>{disposed=true;animations.forEach(a=>a.cancel());dialog.close();document.body.style.overflow=overflow;if(trigger?.isConnected)trigger.focus({preventScroll:true});};},[reduced]);
 return <dialog ref={ref} className="modal notice-modal" aria-labelledby={id} onCancel={event=>{event.preventDefault();close.current();}} onClick={event=>{if(event.target!==event.currentTarget)return;const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close.current();}} onKeyDown={event=>{if(event.key!=='Tab')return;const controls=[...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(e=>e.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}>
 <button className="modal-close icon-button" aria-label="关闭弹层" onClick={()=>close.current()} autoFocus><X size={21}/></button><div className="notice-content"><h2 id={id}>{title}</h2>{children}<button className="text-button dialog-cancel" onClick={()=>close.current()}>关闭</button></div></dialog>;
}
