import {adultBanners} from '../data/adultBanners';
﻿import{useEffect,useMemo,useState,useSyncExternalStore}from'react';
import{Heart,MessageCircle,Copy,Lock,AudioLines,ChevronDown,ChevronUp,BookOpen}from'lucide-react';
import{useReadyScroll}from'../navigation/useReadyScroll';import{useRouter,Link}from'../navigation/Router';
import{Poster}from'./Poster';import{AdultCards,WishButton}from'../adult/AdultCards';import{VideoPlayer}from'./VideoPlayer';import{Breadcrumb}from'./Breadcrumb';import{DialogShell}from'./DialogShell';import{DramaGrid}from'./DramaGrid';
import{useContents}from'../services/hooks';import{greenContext,contentService}from'../services/content';import{adultContext}from'../pages/AdultPages';import{accessService}from'../services/access';import{accountService}from'../services/membership';
import{playableEpisodes,usableSources}from'../data/media';import{demoEpisodes,demoUnlocked,demoPlayback}from'../data/demoPlayback';import{playbackDecision}from'../services/rules';import{records,useRecords}from'../state/records';
import{EmptyState,LoadingState,ErrorState}from'./content/PageParts';import type{Content}from'../types/content';import{formatLabels}from'../types/content';
import{Comments}from'./Comments';
export function PlayPage({id,adult=false,reading=false}:{id:string;adult?:boolean;reading?:boolean}){
 const context=adult?adultContext:greenContext,data=useContents(context);useReadyScroll(!data.loading);const banner=adult?adultBanners.find(c=>c.id===id):undefined;const drama=data.items.find(c=>c.id===id)??(banner&&data.items[0]?{...data.items[0],id:banner.id,title:banner.title,synopsis:banner.synopsis,genre:banner.genre,cover:banner.image,thumbnail:banner.image,largeCover:banner.image,ambient:banner.image}:undefined);
 useEffect(()=>{sessionStorage.setItem('aiai:intro-seen','yes');document.title=adult?'爱爱短剧 · 私密浏览':drama?`${drama.title} · 爱爱短剧`:'爱爱短剧 · 作品详情';return()=>{document.title='爱爱短剧 · 好故事，一眼入戏';};},[drama,adult]);
 if(data.loading)return <main className="container page"><Breadcrumb current="作品详情"/><LoadingState/></main>;
 if(data.error)return <main className="container page"><Breadcrumb current="作品详情"/><ErrorState message={data.error} retry={data.retry}/></main>;
 if(!drama)return <main className="container page"><Breadcrumb current="作品详情"/><EmptyState title="没有找到这部作品"><Link className="primary-button" href={adult?'/18plus':'/#home'}>返回内容首页</Link></EmptyState></main>;
 if(reading&&drama.format!=='article')return <main className="container page"><Breadcrumb current={drama.title}/><EmptyState title="此作品不支持文章阅读"><Link className="primary-button" href={adult?`/18plus/play/${id}`:`/play/${id}`}>查看作品</Link></EmptyState></main>;
 if(drama.format==='article')return <main className="container page"><Breadcrumb current={drama.title}/><h1>{drama.title}</h1><article className="article-body surface-panel"><BookOpen/><p>{drama.body}</p></article></main>;
 return <WatchPage key={id} drama={drama} adult={adult} items={data.items}/>;
}
function WatchPage({drama,adult,items}:{drama:Content;adult:boolean;items:Content[]}){
 const{navigate,route}=useRouter(),account=useSyncExternalStore(accountService.subscribe,accountService.getSnapshot),stored=useRecords();
 const[episode,setEpisode]=useState(0),[group,setGroup]=useState(0),[expanded,setExpanded]=useState(false),[playing,setPlaying]=useState(false),[dialog,setDialog]=useState(''),[lockedTarget,setLockedTarget]=useState<number|null>(null),[copied,setCopied]=useState(''),[autoNext,setAutoNext]=useState(()=>localStorage.getItem('aiai:auto-next')!=='off');
 const demos=useMemo(()=>demoEpisodes(drama,adult&&accessService.isGranted()),[drama,adult]);const isDemo=demos.length>0;
 const formal=drama.format==='article'?[]:playableEpisodes(drama.media);const episodes=isDemo?demos:formal;
 const current=episodes[episode],context=adult?adultContext:greenContext,decision=playbackDecision(drama,context);
 const allowed=!isDemo&&decision.allowed;
 const sources=isDemo?[]:usableSources(formal.length?current?.sources:drama.media?.sources);
 useEffect(()=>{const requested=route.params.get('episode');if(!requested)return;const index=episodes.findIndex(item=>item.id===requested);if(index>=0){setEpisode(index);setGroup(Math.floor(index/demoPlayback.groupSize));}},[drama.id,episodes.length]);
 const choose=(next:number)=>{if(next<0||next>=episodes.length)return;if(isDemo&&!demoUnlocked(demos[next],account.tier)){setLockedTarget(next);setDialog(demos[next].tier==='premium'?'本集需要高级会员权益':'本集需要基础会员权益');return;}setEpisode(next);setGroup(Math.floor(next/demoPlayback.groupSize));setPlaying(false);navigate(`${adult?'/18plus/play/':'/play/'}${encodeURIComponent(drama.id)}?episode=${encodeURIComponent(episodes[next].id)}`,{replace:true,preserveScroll:true});};
 const back=()=>{const origin=history.state?.playOrigin;if(typeof origin==='string'&&/^\/(?:$|\?|#|shorts(?:[?#]|$)|comics(?:[?#]|$)|free(?:[?#]|$)|search(?:[?#]|$)|collections(?:[/?#]|$)|me(?:[?#]|$)|18plus(?:[/?#]|$))/.test(origin)&&!origin.startsWith('//'))history.back();else navigate(adult?'/18plus':'/#home');};
 const favorite=adult?stored.wishlist.includes(drama.id):stored.green.includes(drama.id);
 const toggleFavorite=()=>{if(adult){records.toggleWishlist(drama.id);return;}if(account.status==='guest'){navigate(`/account/login?returnTo=${encodeURIComponent(`${location.pathname}${location.search}`)}`);return;}setDialog('收藏服务暂时不可用');};
 const copy=async()=>{if(adult){setCopied('私密内容不提供公开分享。');return;}try{await navigator.clipboard.writeText(`${location.origin}/play/${encodeURIComponent(drama.id)}`);setCopied('链接已复制');}catch{setCopied('复制未完成，请手动复制浏览器地址。');}};
 const groupCount=Math.ceil(episodes.length/demoPlayback.groupSize);
 return <main className="watch-page container"><Breadcrumb current={drama.title}/><div className="watch-layout"><section className="watch-media" aria-label="播放区域">
 {allowed&&sources.length?<VideoPlayer key={`${drama.id}-${episode}`} custom sources={sources} title={`${drama.title} 第${episode+1}集`} onBack={back} onPrevious={()=>choose(episode-1)} onNext={()=>choose(episode+1)} previousDisabled={episode===0} nextDisabled={episode>=episodes.length-1} onPlaybackChange={setPlaying} onEnded={()=>{if(autoNext&&episode<episodes.length-1)choose(episode+1);}}/>:<div className="watch-unavailable"><button className="text-button" onClick={back}>返回上一列表</button><>{adult&&<div className="adult-detail-poster"><Poster drama={drama} priority/></div>}<EmptyState title="该集暂时无法播放" description="当前没有可用的正式片源，请稍后再试或返回发现其他故事。"><button className="secondary-button" onClick={()=>location.reload()}>重新加载</button></EmptyState></></div>}
 </section><aside className="watch-info" tabIndex={0} aria-label="作品信息与选集"><h1>{drama.title} {episodes.length>0&&<span>第{episode+1}集</span>}</h1><div className="watch-actions">{adult?<WishButton item={drama}/>:<button aria-pressed={favorite} onClick={toggleFavorite}><Heart size={18} fill={favorite?'currentColor':'none'}/>{favorite?'已收藏':'收藏'}</button>}{!adult&&current&&<button onClick={()=>document.getElementById('comments')?.scrollIntoView({behavior:'smooth',block:'start'})}><MessageCircle size={18}/>评论</button>}</div><div className="tag-row">{adult&&<span className="genre-badge">{formatLabels[drama.format]}</span>}<span className="genre-badge">{drama.genre}</span></div>
 {drama.synopsis&&<section className="watch-synopsis"><h2>剧情简介</h2><p className={expanded?'':'collapsed'}>{drama.synopsis}</p>{drama.synopsis.length>65&&<button className="text-button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'收起':'展开'}{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>}</section>}
 <div className="watch-share">{adult?<span>私密内容不提供公开分享</span>:<button className="secondary-button" onClick={()=>void copy()}><Copy size={16}/>复制链接</button>}<span role="status">{copied}</span></div>
 {episodes.length>0&&<section className="watch-episodes" aria-label="剧集列表"><div className="episode-heading"><h2>剧集列表</h2><span>{episodes.length} 集</span></div>{groupCount>1&&<div className="episode-groups" aria-label="剧集范围">{Array.from({length:groupCount},(_,g)=><button key={g} aria-pressed={g===group} onClick={()=>setGroup(g)}>{g*demoPlayback.groupSize+1}–{Math.min((g+1)*demoPlayback.groupSize,episodes.length)}</button>)}</div>}
 <div className="episode-grid">{episodes.slice(group*demoPlayback.groupSize,(group+1)*demoPlayback.groupSize).map((item,i)=>{const index=group*demoPlayback.groupSize+i,locked=isDemo&&!demoUnlocked(demos[index],account.tier);return <button key={item.id} className={locked?'episode-locked':''} aria-label={`第${index+1}集${locked?'，需'+(demos[index].tier==='basic'?'基础':'高级')+'会员权益':''}`} aria-current={index===episode?'true':undefined} onClick={()=>choose(index)}>{index===episode&&playing?<AudioLines size={15}/>:null}<span>{index+1}</span>{locked&&<Lock size={11}/>}</button>;})}</div>
 {!isDemo&&episodes.length>1&&<label className="checkbox-label"><input type="checkbox" checked={autoNext} onChange={e=>{setAutoNext(e.target.checked);localStorage.setItem('aiai:auto-next',e.target.checked?'on':'off');}}/>播完自动播放下一集</label>}
 </section>}
 </aside></div>{!adult&&current&&<Comments key={current.id} dramaId={drama.id} episodeId={current.id} episodeNumber={episode+1}/>}<div className="related-content">{adult?<AdultCards id="adult-related" title="继续发现" items={contentService.recommendations(items,context,drama.id)}/>:<DramaGrid id="related" title="继续发现" subtitle="仅推荐当前内容范围内的作品" items={contentService.recommendations(items,context,drama.id)}/>}</div>{dialog&&<DialogShell title={dialog} hideFooterClose={dialog.startsWith('本集')} onClose={()=>{setDialog('');setLockedTarget(null);}}>{dialog.startsWith('本集')?<><p>开通对应会员后可继续观看本集，返回时会保留当前作品与集数。</p><div className="membership-gate-actions"><Link className="primary-button" href={`/membership?returnTo=${encodeURIComponent(`${location.pathname}?episode=${episodes[lockedTarget??episode]?.id??''}`)}`}>开通会员</Link><button className="secondary-button" onClick={()=>{setDialog('');setLockedTarget(null);}}>暂不观看</button></div></>:<p>请稍后再试。</p>}</DialogShell>}</main>;
}
