import{useEffect,useLayoutEffect,useRef,useState}from'react';
import{Film,RotateCcw,Play,Pause,Volume2,VolumeX,Maximize,Minimize,X,ChevronUp,ChevronDown}from'lucide-react';
import type{VideoSource}from'../data/videoSources';
interface Props{sources:VideoSource[];title:string;custom?:boolean;onBack?:()=>void;onPrevious?:()=>void;onNext?:()=>void;previousDisabled?:boolean;nextDisabled?:boolean;onPlaybackChange?:(playing:boolean)=>void}
const playbackPreferences={volume:.5,muted:true,rate:1};
export const formatTime=(seconds:number)=>{const value=Math.max(0,Number.isFinite(seconds)?Math.floor(seconds):0);return `${Math.floor(value/60).toString().padStart(2,'0')}:${(value%60).toString().padStart(2,'0')}`;};
export function VideoPlayer({sources,title,custom=false,onBack,onPrevious,onNext,previousDisabled,nextDisabled,onPlaybackChange}:Props){
 const[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[attempt,setAttempt]=useState(0),[ratio,setRatio]=useState<number>(),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[volume,setVolume]=useState(()=>custom?playbackPreferences.volume:.5),[muted,setMuted]=useState(()=>custom?playbackPreferences.muted:true),[rate,setRate]=useState(()=>custom?playbackPreferences.rate:1),[full,setFull]=useState(false),[notice,setNotice]=useState('');
 const video=useRef<HTMLVideoElement>(null),stage=useRef<HTMLDivElement>(null),controls=useRef<HTMLDivElement>(null);const sourceKey=sources.map(s=>s.src).join('|');
 useEffect(()=>{const el=video.current!;el.querySelectorAll('source').forEach((s,i)=>{if(sources[i])s.setAttribute('src',sources[i].src);});el.load();setStatus('loading');setTime(0);setDuration(0);setPlaying(false);el.volume=volume;el.muted=muted;el.playbackRate=rate;if(custom)void el.play().catch(()=>{});return()=>{el.pause();el.removeAttribute('src');el.querySelectorAll('source').forEach(s=>s.removeAttribute('src'));el.load();};},[attempt,sourceKey]);
 useLayoutEffect(()=>{if(!custom||!controls.current)return;const measure=()=>stage.current?.style.setProperty('--control-height',`${controls.current!.getBoundingClientRect().height}px`);measure();const observer=new ResizeObserver(measure);observer.observe(controls.current);return()=>observer.disconnect();},[custom]);
 useEffect(()=>{onPlaybackChange?.(playing);},[playing,onPlaybackChange]);
 useEffect(()=>{if(status!=='loading')return;const timer=setTimeout(()=>setStatus('error'),15000);return()=>clearTimeout(timer);},[status,attempt,sourceKey]);
 useEffect(()=>{const listener=()=>setFull(document.fullscreenElement===stage.current);document.addEventListener('fullscreenchange',listener);return()=>document.removeEventListener('fullscreenchange',listener);},[]);
 const toggle=()=>{const el=video.current!;if(el.paused)void el.play().catch(()=>setNotice('请再次点击播放，或重试加载。'));else el.pause();};
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.current?.requestFullscreen();}catch{setNotice('当前浏览器暂不支持全屏，可使用浏览器全屏模式。');}};
 return <div ref={stage} className={`video-stage ${custom?'custom-video':''}`} style={!custom&&ratio?{aspectRatio:Math.max(ratio,.65)}:undefined} data-status={status}>
 <video key={`${sourceKey}-${attempt}`} ref={video} controls={!custom&&status!=='error'} playsInline preload="metadata" muted={muted} aria-label={`${title}视频播放器`} onLoadedMetadata={e=>{const el=e.currentTarget;setRatio(el.videoWidth/el.videoHeight);setDuration(el.duration);setStatus('ready');}} onDurationChange={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onCanPlay={()=>setStatus('ready')} onWaiting={()=>setStatus('loading')} onSeeking={()=>setStatus('loading')} onSeeked={()=>setStatus('ready')} onPlaying={()=>{setPlaying(true);setStatus('ready');}} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onVolumeChange={e=>{setVolume(e.currentTarget.volume);setMuted(e.currentTarget.muted);if(custom){playbackPreferences.volume=e.currentTarget.volume;playbackPreferences.muted=e.currentTarget.muted;}}} onRateChange={e=>{setRate(e.currentTarget.playbackRate);if(custom)playbackPreferences.rate=e.currentTarget.playbackRate;}} onError={()=>setStatus('error')}>
 {sources.map((source,i)=><source key={source.src} src={source.src} type={source.type} onError={()=>{if(i===sources.length-1)setStatus('error');}}/>)}您的浏览器不支持视频播放。</video>
 {custom&&<><button className="player-return" aria-label="返回上一列表" onClick={onBack}><X size={20}/></button><div className="player-episode-nav"><button aria-label="上一集" disabled={previousDisabled} onClick={onPrevious}><ChevronUp/></button><button aria-label="下一集" disabled={nextDisabled} onClick={onNext}><ChevronDown/></button></div>{!playing&&status==='ready'&&<button className="player-center-play" aria-label="开始播放" onClick={toggle}><Play size={28}/></button>}
 <div ref={controls} className="player-controls"><input className="player-seek" type="range" aria-label="播放进度" min="0" max={Number.isFinite(duration)?duration:0} step="0.1" value={Math.min(time,Number.isFinite(duration)?duration:0)} disabled={!duration||status==='error'} onChange={e=>{video.current!.currentTime=+e.target.value;setTime(+e.target.value);}}/><div className="player-toolbar"><button aria-label={playing?'暂停视频':'播放视频'} onClick={toggle} disabled={status==='error'}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><output className="player-time" aria-label="播放时间">{formatTime(time)} / {formatTime(duration)}</output><div className="player-volume"><button aria-label={muted||volume===0?'取消静音':'静音'} onClick={()=>{video.current!.muted=!video.current!.muted;}}>{muted||volume===0?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><input type="range" aria-label="音量" min="0" max="1" step="0.05" value={volume} onChange={e=>{video.current!.volume=+e.target.value;video.current!.muted=false;}}/></div><select aria-label="播放倍速" value={rate} onChange={e=>{video.current!.playbackRate=+e.target.value;}}>{[.5,1,1.25,1.5,2].map(n=><option key={n} value={n}>{n}×</option>)}</select><button aria-label={full?'退出全屏':'全屏'} onClick={()=>void fullscreen()}>{full?<Minimize size={19}/>:<Maximize size={19}/>}</button></div></div></>}
 {status==='loading'&&<div className="video-status" role="status"><span className="loading-ring"/>{duration>0?'正在缓冲…':'正在加载视频…'}</div>}
 {status==='error'&&<div className="video-status video-error" role="alert"><Film size={32}/><h2>视频暂时无法播放</h2><p>片源可能不可用，或浏览器不支持该格式。</p><button className="primary-button" onClick={()=>{setStatus('loading');setAttempt(n=>n+1);}}><RotateCcw size={16}/>重新加载</button></div>}
 {notice&&<p className="player-notice" role="status">{notice}<button aria-label="关闭播放器提示" onClick={()=>setNotice('')}>关闭</button></p>}
 </div>;
}
