import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium}from'@playwright/test';
async function walk(dir){let list=[];for(const entry of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);list.push(...(entry.isDirectory()?await walk(file):[file]));}return list;}
const files=await walk('dist'),legacy=JSON.parse(await fs.readFile('private/legacy/migration.json','utf8'));let text='';for(const file of files.filter(p=>/\.(js|html|css|json|svg|txt)$/.test(p)))text+=await fs.readFile(file,'utf8');const blocked=[...legacy.map(row=>row.title),'专区概念卡','校验并模拟发布','新建草稿','本地编辑员预览','开发预览场景 · 仅本地','/assets/covers/'];const leaks=blocked.filter(s=>text.includes(s));assert.deepEqual(leaks,[]);assert.equal(files.filter(p=>/\.map$/.test(p)||/drama-\d+.*\.webp/.test(p)||/manifest\.json$/.test(p)).length,0);
const browser=await chromium.launch({channel:'chrome'}),page=await browser.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});page.on('request',r=>requests.push(r.url()));await page.emulateMedia({reducedMotion:'reduce'});await page.addInitScript(()=>sessionStorage.setItem('aiai:price-preview','B'));const routes=[];
for(const [width,height]of [[320,812],[390,844],[768,1024],[1280,720],[1920,1080]]){await page.setViewportSize({width,height});for(const route of ['/','/shorts','/comics','/free','/rankings','/collections/everyday-light','/search?q=concept','/18plus','/18plus/play/private-preview-1','/membership','/me','/me/privacy','/admin/content']){await page.goto('http://localhost:4173'+route);await page.waitForTimeout(420);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`${width} ${route}`);assert.equal(await page.locator('[data-zone="adult"]').count(),0);assert.equal(await page.locator('.preview-controls').count(),0);if(route==='/membership')assert.match(await page.locator('.plan-price').first().innerText(),/19/);routes.push({width,height,route,overflow});}}
assert.deepEqual(errors,[]);assert.deepEqual(requests.filter(url=>/adultPreview|AdminPage|private-neutral|\/private\//.test(url)),[]);
// Separate intentional denied probes, not counted as unexpected user-path errors.
const probes=[];for(const route of ['/private/legacy/migration.json','/private/legacy/covers/drama-05.webp','/.local/m4-backup-location.txt','/tests/fixtures/player-test.mp4','/docs/m4/MIGRATION.md']){const r=await page.request.get('http://localhost:5173'+route);const body=await r.body();assert.ok(r.status()===403||r.status()===404,route+' must be denied');probes.push({route,status:r.status(),bytes:body.length});}
await browser.close();const report={at:new Date().toISOString(),files:files.length,bytes:(await Promise.all(files.map(async p=>(await fs.stat(p)).size))).reduce((a,b)=>a+b,0),blockedStrings:blocked.length,leaks,routes,probes,unexpectedErrors:errors,privateRequests:[],note:'Production denies adult access because real eligibility service is unavailable. Not proof of deployed authentication.'};await fs.writeFile('docs/m4/production-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify({files:report.files,routeChecks:routes.length,deniedProbes:probes.length,errors},null,2));
