import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {chromium} from 'playwright';
const assets=await fs.readdir('dist/assets');
assert(!assets.some(f=>f.startsWith('private-preview-')),'DEV image emitted in production');
const js=(await Promise.all(assets.filter(f=>f.endsWith('.js')).map(f=>fs.readFile(path.join('dist/assets',f),'utf8')))).join('\n');
assert(!js.includes('NetShort_32565ec202039b66'),'DEV mapping emitted');
assert(!js.includes('/src/dev/assets/'),'DEV image URL emitted');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}}),requests=[],errors=[];
page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{localStorage.setItem('adultGranted','true');sessionStorage.setItem('aiai:adult-granted','true');});
await page.goto('http://localhost:4173/18plus/play/private-preview-1');
await page.getByRole('heading',{name:'进入18+专区',exact:true}).waitFor();
assert.equal(await page.locator('.adult-card, .adult-main-poster, video').count(),0);
assert.equal(await page.getByLabel('地区流程场景').count(),0);
assert.equal(await page.getByRole('button',{name:'确认并进入',exact:true}).isEnabled(),true);
await page.getByRole('button',{name:'确认并进入',exact:true}).click();
await page.getByText('内容服务尚未接入',{exact:true}).waitFor();
assert.equal(await page.locator('video,.adult-detail-poster').count(),0);
assert(!requests.some(u=>u.includes('private-preview-')&&!u.includes('/18plus/play/')));
assert.deepEqual(errors,[]);
await fs.mkdir('docs/adult/screenshots',{recursive:true});await page.screenshot({path:'docs/adult-direction/production-service.png',fullPage:true});
const report={productionGate:'one-click session acknowledgement; production content service remains unavailable',developmentImagesInProduction:0,developmentPanelInProduction:false,mediaElements:0,consoleErrors:errors,checkedAt:new Date().toISOString()};
await fs.writeFile('docs/adult/production-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
