import {FestivalStrip} from './components/FestivalArtwork';
﻿import{useCallback,useEffect,useRef,useState}from'react';
import{ArrowUpRight}from'lucide-react';
import{Header}from'./components/Header';import{Intro}from'./components/Intro';import{Carousel}from'./components/Carousel';import{Filters}from'./components/Filters';import{DramaGrid}from'./components/DramaGrid';import{Footer}from'./components/Footer';
import{timing}from'./config';import{useReducedMotion}from'./hooks/useReducedMotion';import{cancelResultsTransition}from'./motion/transitions';import{readHomeState,saveHomeState}from'./navigation/homeState';import{Link,useRouter}from'./navigation/Router';import{useHomeNavigation}from'./navigation/useHomeNavigation';import{useContents}from'./services/hooks';import{greenContext}from'./services/content';import{filterInZone}from'./services/rules';import{EmptyState,ErrorState,LoadingState}from'./components/content/PageParts';import{track}from'./services/analytics';
import{demoStore}from'./services/demoStore';
function firstVisit(){try{return sessionStorage.getItem('aiai:intro-seen')!=='yes';}catch{return true;}}
export function HomePage({onAccount,blocked}:{onAccount:()=>void;blocked:boolean}){
 const[saved]=useState(readHomeState);const[query,setQuery]=useState(saved.query),[selected,setSelected]=useState(saved.genre),[criteria,setCriteria]=useState({query:saved.query,genre:saved.genre});const timer=useRef<number|undefined>(undefined),genreRef=useRef(selected),queryRef=useRef(query);const{replaceHash,navigate}=useRouter();
 const[entering,setEntering]=useState(firstVisit);const logoRef=useRef<HTMLImageElement>(null);const reduced=useReducedMotion();const data=useContents();const progress:ReturnType<typeof demoStore.progress>=[];
 const finishIntro=useCallback(()=>{setEntering(false);try{sessionStorage.setItem('aiai:intro-seen','yes');}catch{/* optional */}},[]);
 useHomeNavigation(entering||data.loading);
 useEffect(()=>{const scroll=()=>saveHomeState({scroll:scrollY});window.addEventListener('scroll',scroll,{passive:true});return()=>{clearTimeout(timer.current);cancelResultsTransition();window.removeEventListener('scroll',scroll);};},[]);
 const commit=(value:string,genre:string)=>{setCriteria({query:value,genre});replaceHash('#popular');};
 const search=(value:string,composing=false)=>{setQuery(value);queryRef.current=value;saveHomeState({query:value});clearTimeout(timer.current);if(composing)return;if(!value.trim())commit('',genreRef.current);else timer.current=window.setTimeout(()=>commit(value,genreRef.current),timing.searchDebounce);};
 const select=(genre:string)=>{clearTimeout(timer.current);genreRef.current=genre;setSelected(genre);saveHomeState({genre});commit(queryRef.current,genre);};
 const results=filterInZone(criteria.query.trim()?data.items:data.items.slice(0,12),greenContext,criteria.query,criteria.genre);
 const featured=data.items.slice(0,5),latest=data.items.slice(12);
 return <><div id="home" tabIndex={-1} className={`app ${entering?'is-entering':''}`} inert={entering}><a href="#browse" className="skip-link">跳到短剧内容</a><Header logoRef={logoRef} query={query} onSearch={search} onSubmitSearch={()=>{clearTimeout(timer.current);track({name:'search_submit',zone:'green'});navigate(`/search?q=${encodeURIComponent(queryRef.current.trim())}`);}} onAccount={onAccount}/>
 <main>{data.loading?<div className="hero-loading"><LoadingState/></div>:<Carousel items={featured} initialId={saved.selectedId} initialIndex={saved.index} initialPaused={saved.paused} reduced={reduced} blocked={entering||blocked} onPositionChange={(index,selectedId,paused)=>saveHomeState({index,selectedId,paused})}/>}
 <div className="container content">{progress.length>0&&<section className="continue-strip"><div className="section-heading"><div><h2>继续观看</h2><p>仅你登录后可见</p></div><Link className="text-button" href="/me/history">全部历史</Link></div><div>{progress.map(item=>{const drama=data.items.find(d=>d.id===item.dramaId);return <Link className="surface-panel" key={item.dramaId} href={`/play/${item.dramaId}?episode=${encodeURIComponent(item.episodeId)}`}><strong>{drama?.title||'已下架作品'}</strong><span>第 {item.episodeNumber} 集 · {Math.min(100,Math.round(item.seconds/item.duration*100))}%</span><ArrowUpRight size={16}/></Link>})}</div></section>}
 <FestivalStrip/><div className="results-wrapper"><DramaGrid id="popular" title="热门推荐" subtitle="精选好故事，下一部心动就在这里" items={results} controls={<Filters selected={selected} onSelect={select}/>} empty={data.error?<ErrorState message={data.error} retry={data.retry}/>:data.loading?<LoadingState/>:<EmptyState title="还没找到这部故事" description="换个题材或关键词，继续发现好故事。"/>}/><DramaGrid id="latest" title="最新更新" subtitle="发现新故事，让期待继续" items={latest} latest/></div>
 </div></main><Footer/></div>{entering&&<Intro logoRef={logoRef} reduced={reduced} onDone={finishIntro}/>}</>;
}
